
//var myCacheVersion = "v.1.2.2024.10.26";






//https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#basic_architecture
const registerServiceWorker = async () => {
  if ("serviceWorker" in navigator) {
    try {
      const registration = await navigator.serviceWorker.register("/sw.js", {
        scope: "/",
      });
      if (registration.installing) {
        console.log("Service worker installing");
      } else if (registration.waiting) {
        console.log("Service worker installed");
  
    } else if (registration.active) {



}
    } catch (error) {

console.error(`Registration failed with ` + error);
    }
  }
};



registerServiceWorker();
swJsInstallFiles();



// fu hide file extension
function hideLinkExt(url){
var linkExtList = ["index.html", ".html"];
var newURL = url;

linkExtList.forEach((element) => {
newURL = newURL.replace(element, '');
});

return newURL;
}
//














function swJsInstallFiles(){

/*
// cache
//https://stackoverflow.com/questions/66529102/uncaught-in-promise-typeerror-failed-to-execute-cache-on-addall-request
//https://github.com/mdn/pwa-examples
self.addEventListener('install', (e) => {
e.waitUntil(caches.open("v.1.2.2024.10.26").then((cache) => cache.addAll(fileListArrFound)),);
});*/





// add files to cache
// cache
//https://developer.mozilla.org/en-US/docs/Web/API/Cache/addAll

self.addEventListener('install', (e) => {


// start check 404, file list 2
var fileListArr = ["/404.html",
"/BingSiteAuth.xml",
"/LICENSE.md",
"/README.md",
"/archive.html",
"/audio/click.mp3",
"/audio/",
"/audio/click2.mp3",
"/audio/error.mp3",
"/audio/game-over.mp3",
"/audio/neutral.mp3",
"/audio/ok.mp3",
"/audio/win.mp3",
"/css/a-backup-old.css",
"/css/",
"/css/auto.css",
"/css/bad.css",
"/css/d-blue.css",
"/css/d-forest.css",
"/css/d-green.css",
"/css/d-orange.css",
"/css/d-pink.css",
"/css/d-plum.css",
"/css/d-purple.css",
"/css/d-red.css",
"/css/d-sea.css",
"/css/d-slate.css",
"/css/d-violet.css",
"/css/d-yellow.css",
"/css/dark.css",
"/css/empty.css",
"/css/h-contrast-d.css",
"/css/h-contrast-l.css",
"/css/l-blue.css",
"/css/l-green.css",
"/css/l-merino.css",
"/css/l-olive.css",
"/css/l-orange.css",
"/css/l-pink.css",
"/css/l-plum.css",
"/css/l-purple.css",
"/css/l-red.css",
"/css/l-sea.css",
"/css/l-seashell.css",
"/css/l-violet.css",
"/css/l-yellow.css",
"/css/light.css",
"/css/main.css",
"/css/noscript.css",
"/css/o-blue.css",
"/css/o-green.css",
"/css/o-lime.css",
"/css/o-mint.css",
"/css/o-olive.css",
"/css/o-orange.css",
"/css/o-pink.css",
"/css/o-plum.css",
"/css/o-purple.css",
"/css/o-red.css",
"/css/o-sea.css",
"/css/o-silver.css",
"/css/o-violet.css",
"/css/o-yellow.css",
"/css/od-blue-2.css",
"/css/od-blue.css",
"/css/od-brown.css",
"/css/od-forest.css",
"/css/od-gray.css",
"/css/od-green.css",
"/css/od-olive.css",
"/css/od-pink.css",
"/css/od-plum.css",
"/css/od-purple.css",
"/css/od-red.css",
"/css/od-sea.css",
"/css/od-slate.css",
"/css/od-violet.css",
"/css/od-yellow.css",
"/css/rss.css",
"/css/style.css",
"/data/ads.json",
"/data/",
"/data/adsJsonVar.js",
"/data/agicountdown.json",
"/data/agicountdownJsonVar.js",
"/data/articles.json",
"/data/articlesJsonVar.js",
"/data/book.json",
"/data/bookJsonVar.js",
"/data/iconsJsonVar.js",
"/data/links.json",
"/data/linksJsonVar.js",
"/data/microblog.json",
"/data/microblogJsonVar.js",
"/data/music.json",
"/data/musicJsonVar.js",
"/data/news.json",
"/data/newsJsonVar.js",
"/data/notes.json",
"/data/notesJsonVar.js",
"/data/podcast.json",
"/data/podcastJsonVar.js",
"/data/posts.json",
"/data/postsJsonVar.js",
"/data/quiz.json",
"/data/quizJsonVar.js",
"/data/quote.json",
"/data/quoteJsonVar.js",
"/data/radio.json",
"/data/radioJsonVar.js",
"/data/randomwebsite.json",
"/data/randomwebsiteJsonVar.js",
"/data/tv.json",
"/data/tvJsonVar.js",
"/data/video.json",
"/data/videoJsonVar.js",
"/data/word.json",
"/data/wordJsonVar.js",
"/data2/WATCHLIST.csv",
"/data2/",
"/favicon.ico",
"/games/dice-9/index.html",
"/games/",
"/games/dice-9/",
"/games/dice-9/script.js",
"/games/dice-9/style.css",
"/games/guess-number-10/index.html",
"/games/guess-number-10/",
"/games/guess-number-10/script.js",
"/games/guess-number-10/style.css",
"/games/index.html",
"/games/lnnguage-learning-quiz-45/index.html",
"/games/lnnguage-learning-quiz-45/",
"/games/lnnguage-learning-quiz-45/script (copy 1).js",
"/games/lnnguage-learning-quiz-45/script.js",
"/games/lnnguage-learning-quiz-45/style.css",
"/games/memory-symbol-11/index.html",
"/games/memory-symbol-11/",
"/games/memory-symbol-11/script.js",
"/games/memory-symbol-11/style.css",
"/games/quiz-42/index.html",
"/games/quiz-42/",
"/games/quiz-42/script (copy 1).js",
"/games/quiz-42/script (copy 2).js",
"/games/quiz-42/script.js",
"/games/quiz-42/style.css",
"/games/rock-paper-scissors-67/index.html",
"/games/rock-paper-scissors-67/",
"/games/rock-paper-scissors-67/script.js",
"/games/rock-paper-scissors-67/style.css",
"/games/snake-12/index.html",
"/games/snake-12/",
"/games/snake-12/script.js",
"/games/snake-12/style.css",
"/games/spin-wheel-69/index.html",
"/games/spin-wheel-69/",
"/games/spin-wheel-69/script.js",
"/games/spin-wheel-69/style.css",
"/games/tic-tac-toe-13/index.html",
"/games/tic-tac-toe-13/",
"/games/tic-tac-toe-13/script.js",
"/games/tic-tac-toe-13/style.css",
"/games/typing-speed-14/index.html",
"/games/typing-speed-14/",
"/games/typing-speed-14/script (copy 1).js",
"/games/typing-speed-14/script.js",
"/games/typing-speed-14/style.css",
"/games-list.html",
"/googlebb934aafeeb1ecb6.html",
"/img/404.png",
"/img/",
"/img/404.svg",
"/img/bg-binary-d.svg",
"/img/bg-binary.svg",
"/img/bg-circle-d.svg",
"/img/bg-circle.svg",
"/img/bg-deco-paper-d.svg",
"/img/bg-deco-paper.svg",
"/img/bg-index-d.svg",
"/img/bg-index.svg",
"/img/bg-line-chaotic-d.svg",
"/img/bg-line-chaotic.svg",
"/img/bg-line-square-d.svg",
"/img/bg-line-square.svg",
"/img/bg-shape-d.svg",
"/img/bg-shape.svg",
"/img/bg-short-line-d.svg",
"/img/bg-short-line.svg",
"/img/bg-square-solid-d.svg",
"/img/bg-square-solid.svg",
"/img/bg-star-d.svg",
"/img/bg-star.svg",
"/img/bg-triangle-d.svg",
"/img/bg-triangle.svg",
"/img/bg-wood-d.svg",
"/img/bg-wood.svg",
"/img/example.png",
"/img/example.svg",
"/img/github-banner-settings.png",
"/img/github-banner-settings.svg",
"/img/header-banner (copy 1).svg",
"/img/header-banner.png",
"/img/header-banner.svg",
"/img/logo-gray.png",
"/img/logo.png",
"/img/logo.svg",
"/img/maskable_logo.png",
"/img/maskable_logo_gray.png",
"/img/repository-open-graph-template.png",
"/img/screenshot.png",
"/img/screenshot2.png",
"/img/tpl/ava.png",
"/img/tpl/",
"/img/tpl/ava.svg",
"/img/tpl/bg-dark.png",
"/img/tpl/bg-dark.svg",
"/img/tpl/bg-light.png",
"/img/tpl/bg.svg",
"/img/tpl/favicon.ico",
"/img/tpl/favicon.png",
"/img/tpl/flower.png",
"/img/tpl/flower.svg",
"/img/tpl/header-banner.svg",
"/img/tpl/image.png",
"/img/tpl/logo.png",
"/img/tpl/logo.svg",
"/img/tpl/logo2.png",
"/img/tpl/logo2.svg",
"/img/tpl/photo.jpg",
"/img/tpl/photo2.jpg",
"/img/tpl/tree.svg",
"/img/tpl/woman.png",
"/img/tpl/woman.svg",
"/img/transparent.png",
"/img/transparent.svg",
"/index.html",
"/js/ads.js",
"/js/",
"/js/backup.txt.js",
"/js/cookieAgreePopup.js",
"/js/fuPostTime.js",
"/js/main.js",
"/js/script (copy 1).js",
"/js/script.js",
"/js/settings-options.js",
"/js/theme-options.js",
"/manifest.webmanifest",
"/mini-projects/animated-borders-button-link-5/index.html",
"/mini-projects/",
"/mini-projects/animated-borders-button-link-5/",
"/mini-projects/animated-borders-button-link-5/style.css",
"/mini-projects/animation-test-6/index.html",
"/mini-projects/animation-test-6/",
"/mini-projects/animation-test-6/style.css",
"/mini-projects/background-with-linear-gradient-css-7/index.html",
"/mini-projects/background-with-linear-gradient-css-7/",
"/mini-projects/background-with-linear-gradient-css-7/style.css",
"/mini-projects/button-blur-unblur-28/index.html",
"/mini-projects/button-blur-unblur-28/",
"/mini-projects/button-blur-unblur-28/style.css",
"/mini-projects/flex-grid-32/index.html",
"/mini-projects/flex-grid-32/",
"/mini-projects/flex-grid-32/style.css",
"/mini-projects/heading-33/index.html",
"/mini-projects/heading-33/",
"/mini-projects/heading-33/style.css",
"/mini-projects/hide-show-on-resize-35/index.html",
"/mini-projects/hide-show-on-resize-35/",
"/mini-projects/hide-show-on-resize-35/style.css",
"/mini-projects/html-symbols-36/index.html",
"/mini-projects/html-symbols-36/",
"/mini-projects/html-symbols-36/style.css",
"/mini-projects/index.html",
"/mini-projects/light-and-dark-design-29/index.html",
"/mini-projects/light-and-dark-design-29/",
"/mini-projects/light-and-dark-design-29/style.css",
"/mini-projects/palette-generator-using-css-34/index.html",
"/mini-projects/palette-generator-using-css-34/",
"/mini-projects/palette-generator-using-css-34/style.css",
"/mini-projects/project-ideas-37/index.html",
"/mini-projects/project-ideas-37/",
"/mini-projects/project-ideas-37/style.css",
"/mini-projects/responsive-web-design-2/index.html",
"/mini-projects/responsive-web-design-2/",
"/mini-projects/responsive-web-design-2/script.js",
"/mini-projects/responsive-web-design-2/style.css",
"/mini-projects/simple-page-38/index.html",
"/mini-projects/simple-page-38/",
"/mini-projects/simple-page-38/style.css",
"/mini-projects/sun-and-moon-css-31/index.html",
"/mini-projects/sun-and-moon-css-31/",
"/mini-projects/sun-and-moon-css-31/style.css",
"/mini-projects/tpl-project-mini-1/index.html",
"/mini-projects/tpl-project-mini-1/",
"/mini-projects/tpl-project-mini-1/style.css",
"/mini-projects-list.html",
"/old-projects/blocked-65/index.html",
"/old-projects/",
"/old-projects/blocked-65/",
"/old-projects/blocked-65/script.js",
"/old-projects/blocked-65/style.css",
"/old-projects/hello-world-62/index.html",
"/old-projects/hello-world-62/",
"/old-projects/hello-world-62/script.js",
"/old-projects/hello-world-62/style.css",
"/old-projects/index.html",
"/old-projects/not-sleep-pc-12/index.html",
"/old-projects/not-sleep-pc-12/",
"/old-projects/not-sleep-pc-12/style.css",
"/old-projects/pwa-test-21/index.html",
"/old-projects/pwa-test-21/",
"/old-projects/pwa-test-21/manifest.webmanifest",
"/old-projects/pwa-test-21/script.js",
"/old-projects/pwa-test-21/style.css",
"/old-projects/pwa-test-21/sw.js",
"/old-projects/textarea-24/index.html",
"/old-projects/textarea-24/",
"/old-projects/textarea-24/style.css",
"/old-projects-list.html",
"/other-projects/index.html",
"/other-projects/",
"/other-projects/other/dreamwidth.org-style-backup/auto-generated-layer.txt",
"/other-projects/other/",
"/other-projects/other/dreamwidth.org-style-backup/",
"/other-projects/other/dreamwidth.org-style-backup/style.css",
"/other-projects/php/hello-world/index.php",
"/other-projects/php/",
"/other-projects/php/hello-world/",
"/other-projects/php/index.html",
"/other-projects/php/php-site-to-static-site-in-progress/generator.php",
"/other-projects/php/php-site-to-static-site-in-progress/",
"/other-projects/php/php-site-to-static-site-in-progress/index.php",
"/other-projects/php/website-to-pwa/index.php",
"/other-projects/php/website-to-pwa/",
"/other-projects/php/website-to-pwa/websiteToPwa.php",
"/other-projects/php/website-to-pwa/websiteToPwa2HidenExt.php",
"/other-projects/python/hello-world/main.py",
"/other-projects/python/",
"/other-projects/python/hello-world/",
"/other-projects/python/index.html",
"/other-projects-list.html",
"/pages/about.html",
"/pages/",
"/pages/ads.html",
"/pages/art.html",
"/pages/articles.html",
"/pages/chrome-extensions.html",
"/pages/chrome-theme.html",
"/pages/css-art.html",
"/pages/data-page.html",
"/pages/firefox-extensions.html",
"/pages/firefox-theme.html",
"/pages/geany-theme.html",
"/pages/icons.html",
"/pages/images.html",
"/pages/index.html",
"/pages/install.html",
"/pages/links.html",
"/pages/microblog.html",
"/pages/news.html",
"/pages/notes.html",
"/pages/other-data-page.html",
"/pages/photos.html",
"/pages/posts.html",
"/pages/search.html",
"/pages/settings.html",
"/pages/site-search.html",
"/pages/templates.html",
"/pages/themes.html",
"/pages/updates.html",
"/pages-data/art/2024/car-gimp-6.jpg",
"/pages-data/",
"/pages-data/art/",
"/pages-data/art/2024/",
"/pages-data/art/2024/cloud-gimp-7.jpg",
"/pages-data/art/2024/empty-drawing-1.png",
"/pages-data/art/2024/face-gimp-10.jpg",
"/pages-data/art/2024/https-paint-toys-calligram-screenshot-2.png",
"/pages-data/art/2024/https-paint-toys-mondrian-screenshot-3.png",
"/pages-data/art/2024/https-paint-toys-oil-screenshot-4.png",
"/pages-data/art/2024/https-paint-toys-one-line-screenshot-5.jpeg",
"/pages-data/art/2024/update-lemon-gimp-11.jpg",
"/pages-data/art/2024/wave-lines-gimp-8.jpg",
"/pages-data/art/2024/window-gimp-9.jpg",
"/pages-data/art/index.html",
"/pages-data/chrome-extensions/README.md",
"/pages-data/chrome-extensions/",
"/pages-data/chrome-extensions/badge-count-up-timer-4/auto.css",
"/pages-data/chrome-extensions/badge-count-up-timer-4/",
"/pages-data/chrome-extensions/badge-count-up-timer-4/background.js",
"/pages-data/chrome-extensions/badge-count-up-timer-4/icon512x512.png",
"/pages-data/chrome-extensions/badge-count-up-timer-4/icon512x512.svg",
"/pages-data/chrome-extensions/badge-count-up-timer-4/main.css",
"/pages-data/chrome-extensions/badge-count-up-timer-4/manifest.json",
"/pages-data/chrome-extensions/badge-count-up-timer-4/popup.html",
"/pages-data/chrome-extensions/badge-count-up-timer-4/script.js",
"/pages-data/chrome-extensions/badge-count-up-timer-4/style.css",
"/pages-data/chrome-extensions/badge-count-up-timer-4.crx",
"/pages-data/chrome-extensions/hotkey-url-5/README.md",
"/pages-data/chrome-extensions/hotkey-url-5/",
"/pages-data/chrome-extensions/hotkey-url-5/a-backup-old.css",
"/pages-data/chrome-extensions/hotkey-url-5/auto.css",
"/pages-data/chrome-extensions/hotkey-url-5/icon512x512.png",
"/pages-data/chrome-extensions/hotkey-url-5/icon512x512.svg",
"/pages-data/chrome-extensions/hotkey-url-5/main.css",
"/pages-data/chrome-extensions/hotkey-url-5/manifest.json",
"/pages-data/chrome-extensions/hotkey-url-5/options.html",
"/pages-data/chrome-extensions/hotkey-url-5/options.js",
"/pages-data/chrome-extensions/hotkey-url-5/screenshot.png",
"/pages-data/chrome-extensions/hotkey-url-5/script.js",
"/pages-data/chrome-extensions/hotkey-url-5/style-main.css",
"/pages-data/chrome-extensions/hotkey-url-5/style.css",
"/pages-data/chrome-extensions/hotkey-url-5/worker.js",
"/pages-data/chrome-extensions/hotkey-url-5.crx",
"/pages-data/chrome-extensions/index.html",
"/pages-data/chrome-extensions/new-tab-redirect-3/README.md",
"/pages-data/chrome-extensions/new-tab-redirect-3/",
"/pages-data/chrome-extensions/new-tab-redirect-3/a-backup-old.css",
"/pages-data/chrome-extensions/new-tab-redirect-3/icon512x512.png",
"/pages-data/chrome-extensions/new-tab-redirect-3/icon512x512.svg",
"/pages-data/chrome-extensions/new-tab-redirect-3/light.css",
"/pages-data/chrome-extensions/new-tab-redirect-3/main.css",
"/pages-data/chrome-extensions/new-tab-redirect-3/manifest.json",
"/pages-data/chrome-extensions/new-tab-redirect-3/new-tab-redirect.html",
"/pages-data/chrome-extensions/new-tab-redirect-3/options.html",
"/pages-data/chrome-extensions/new-tab-redirect-3/options.js",
"/pages-data/chrome-extensions/new-tab-redirect-3/screenshot.png",
"/pages-data/chrome-extensions/new-tab-redirect-3/screenshot2.png",
"/pages-data/chrome-extensions/new-tab-redirect-3/script.js",
"/pages-data/chrome-extensions/new-tab-redirect-3/style.css",
"/pages-data/chrome-extensions/new-tab-redirect-3.crx",
"/pages-data/chrome-extensions/stop-loading-website-7/README.md",
"/pages-data/chrome-extensions/stop-loading-website-7/",
"/pages-data/chrome-extensions/stop-loading-website-7/auto.css",
"/pages-data/chrome-extensions/stop-loading-website-7/icon512x512.png",
"/pages-data/chrome-extensions/stop-loading-website-7/icon512x512.svg",
"/pages-data/chrome-extensions/stop-loading-website-7/main.css",
"/pages-data/chrome-extensions/stop-loading-website-7/manifest.json",
"/pages-data/chrome-extensions/stop-loading-website-7/options.html",
"/pages-data/chrome-extensions/stop-loading-website-7/options.js",
"/pages-data/chrome-extensions/stop-loading-website-7/screenshot.png",
"/pages-data/chrome-extensions/stop-loading-website-7/script.js",
"/pages-data/chrome-extensions/stop-loading-website-7/style.css",
"/pages-data/chrome-extensions/url-redirect-6/README.md",
"/pages-data/chrome-extensions/url-redirect-6/",
"/pages-data/chrome-extensions/url-redirect-6/auto.css",
"/pages-data/chrome-extensions/url-redirect-6/icon512x512.png",
"/pages-data/chrome-extensions/url-redirect-6/icon512x512.svg",
"/pages-data/chrome-extensions/url-redirect-6/main.css",
"/pages-data/chrome-extensions/url-redirect-6/manifest.json",
"/pages-data/chrome-extensions/url-redirect-6/options.html",
"/pages-data/chrome-extensions/url-redirect-6/options.js",
"/pages-data/chrome-extensions/url-redirect-6/screenshot.png",
"/pages-data/chrome-extensions/url-redirect-6/script.js",
"/pages-data/chrome-extensions/url-redirect-6/style.css",
"/pages-data/chrome-extensions/url-redirect-6/url-redirect-6.zip",
"/pages-data/chrome-extensions/url-redirect-6.crx",
"/pages-data/chrome-theme/Source.txt",
"/pages-data/chrome-theme/",
"/pages-data/chrome-theme/dark-theme/manifest.json",
"/pages-data/chrome-theme/dark-theme/",
"/pages-data/chrome-theme/dark-theme.crx",
"/pages-data/chrome-theme/dark-theme.png",
"/pages-data/chrome-theme/index.html",
"/pages-data/chrome-theme/light-theme/manifest.json",
"/pages-data/chrome-theme/light-theme/",
"/pages-data/chrome-theme/light-theme.crx",
"/pages-data/chrome-theme/light-theme.png",
"/pages-data/chrome-theme/tpl-theme/manifest.json",
"/pages-data/chrome-theme/tpl-theme/",
"/pages-data/css-art/computer-css-9/index.html",
"/pages-data/css-art/",
"/pages-data/css-art/computer-css-9/",
"/pages-data/css-art/computer-css-9/style.css",
"/pages-data/css-art/halloween-pumpkin-css-15/index.html",
"/pages-data/css-art/halloween-pumpkin-css-15/",
"/pages-data/css-art/halloween-pumpkin-css-15/style.css",
"/pages-data/css-art/index.html",
"/pages-data/css-art/realistic-old-windows-os-popup-window-12/index.html",
"/pages-data/css-art/realistic-old-windows-os-popup-window-12/",
"/pages-data/css-art/realistic-old-windows-os-popup-window-12/style.css",
"/pages-data/css-art/tpl-0/index.html",
"/pages-data/css-art/tpl-0/",
"/pages-data/css-art/tpl-0/style.css",
"/pages-data/css-art/woman-css-32/index.html",
"/pages-data/css-art/woman-css-32/",
"/pages-data/css-art/woman-css-32/style.css",
"/pages-data/firefox-extensions/hotkey-url-5/README.md",
"/pages-data/firefox-extensions/",
"/pages-data/firefox-extensions/hotkey-url-5/",
"/pages-data/firefox-extensions/hotkey-url-5/hotkey-url-5.zip",
"/pages-data/firefox-extensions/hotkey-url-5/icon512x512.png",
"/pages-data/firefox-extensions/hotkey-url-5/icon512x512.svg",
"/pages-data/firefox-extensions/hotkey-url-5/main.css",
"/pages-data/firefox-extensions/hotkey-url-5/manifest.json",
"/pages-data/firefox-extensions/hotkey-url-5/options.html",
"/pages-data/firefox-extensions/hotkey-url-5/options.js",
"/pages-data/firefox-extensions/hotkey-url-5/screenshot.png",
"/pages-data/firefox-extensions/hotkey-url-5/script.js",
"/pages-data/firefox-extensions/hotkey-url-5/style.css",
"/pages-data/firefox-extensions/hotkey-url-5/worker.js",
"/pages-data/firefox-extensions/index.html",
"/pages-data/firefox-extensions/new-tab-redirect-3/README.md",
"/pages-data/firefox-extensions/new-tab-redirect-3/",
"/pages-data/firefox-extensions/new-tab-redirect-3/auto.css",
"/pages-data/firefox-extensions/new-tab-redirect-3/icon512x512.png",
"/pages-data/firefox-extensions/new-tab-redirect-3/icon512x512.svg",
"/pages-data/firefox-extensions/new-tab-redirect-3/main.css",
"/pages-data/firefox-extensions/new-tab-redirect-3/manifest.json",
"/pages-data/firefox-extensions/new-tab-redirect-3/new-tab-redirect-3.zip",
"/pages-data/firefox-extensions/new-tab-redirect-3/new-tab-redirect.html",
"/pages-data/firefox-extensions/new-tab-redirect-3/options.html",
"/pages-data/firefox-extensions/new-tab-redirect-3/options.js",
"/pages-data/firefox-extensions/new-tab-redirect-3/screenshot.png",
"/pages-data/firefox-extensions/new-tab-redirect-3/screenshot2.png",
"/pages-data/firefox-extensions/new-tab-redirect-3/screenshot3.png",
"/pages-data/firefox-extensions/new-tab-redirect-3/script.js",
"/pages-data/firefox-extensions/new-tab-redirect-3/style.css",
"/pages-data/firefox-extensions/old/badge-count-up-timer-4/README.md",
"/pages-data/firefox-extensions/old/",
"/pages-data/firefox-extensions/old/badge-count-up-timer-4/",
"/pages-data/firefox-extensions/old/badge-count-up-timer-4/auto.css",
"/pages-data/firefox-extensions/old/badge-count-up-timer-4/background.html",
"/pages-data/firefox-extensions/old/badge-count-up-timer-4/background.js",
"/pages-data/firefox-extensions/old/badge-count-up-timer-4/badge-count-up-timer-4.zip",
"/pages-data/firefox-extensions/old/badge-count-up-timer-4/icon512x512.png",
"/pages-data/firefox-extensions/old/badge-count-up-timer-4/icon512x512.svg",
"/pages-data/firefox-extensions/old/badge-count-up-timer-4/main.css",
"/pages-data/firefox-extensions/old/badge-count-up-timer-4/manifest.json",
"/pages-data/firefox-extensions/old/badge-count-up-timer-4/popup.html",
"/pages-data/firefox-extensions/old/badge-count-up-timer-4/screenshot.png",
"/pages-data/firefox-extensions/old/badge-count-up-timer-4/script.js",
"/pages-data/firefox-extensions/old/badge-count-up-timer-4/style.css",
"/pages-data/firefox-extensions/search-localhost-http-1/icon512x512.png",
"/pages-data/firefox-extensions/search-localhost-http-1/",
"/pages-data/firefox-extensions/search-localhost-http-1/icon512x512.svg",
"/pages-data/firefox-extensions/search-localhost-http-1/manifest.json",
"/pages-data/firefox-extensions/search-localhost-http-1/search-localhost-http-1.zip",
"/pages-data/firefox-extensions/search-localhost-https-2/icon512x512.png",
"/pages-data/firefox-extensions/search-localhost-https-2/",
"/pages-data/firefox-extensions/search-localhost-https-2/icon512x512.svg",
"/pages-data/firefox-extensions/search-localhost-https-2/manifest.json",
"/pages-data/firefox-extensions/search-localhost-https-2/search-localhost-https-2.zip",
"/pages-data/firefox-extensions/stop-loading-website-7/README.md",
"/pages-data/firefox-extensions/stop-loading-website-7/",
"/pages-data/firefox-extensions/stop-loading-website-7/auto.css",
"/pages-data/firefox-extensions/stop-loading-website-7/icon512x512.png",
"/pages-data/firefox-extensions/stop-loading-website-7/icon512x512.svg",
"/pages-data/firefox-extensions/stop-loading-website-7/main.css",
"/pages-data/firefox-extensions/stop-loading-website-7/manifest.json",
"/pages-data/firefox-extensions/stop-loading-website-7/options.html",
"/pages-data/firefox-extensions/stop-loading-website-7/options.js",
"/pages-data/firefox-extensions/stop-loading-website-7/screenshot.png",
"/pages-data/firefox-extensions/stop-loading-website-7/script.js",
"/pages-data/firefox-extensions/stop-loading-website-7/stop-loading-website-7.zip",
"/pages-data/firefox-extensions/stop-loading-website-7/style.css",
"/pages-data/firefox-extensions/url-redirect-6/README.md",
"/pages-data/firefox-extensions/url-redirect-6/",
"/pages-data/firefox-extensions/url-redirect-6/auto.css",
"/pages-data/firefox-extensions/url-redirect-6/icon512x512.png",
"/pages-data/firefox-extensions/url-redirect-6/icon512x512.svg",
"/pages-data/firefox-extensions/url-redirect-6/main.css",
"/pages-data/firefox-extensions/url-redirect-6/manifest.json",
"/pages-data/firefox-extensions/url-redirect-6/options.html",
"/pages-data/firefox-extensions/url-redirect-6/options.js",
"/pages-data/firefox-extensions/url-redirect-6/screenshot.png",
"/pages-data/firefox-extensions/url-redirect-6/script.js",
"/pages-data/firefox-extensions/url-redirect-6/style.css",
"/pages-data/firefox-extensions/url-redirect-6/url-redirect-6.zip",
"/pages-data/firefox-theme/README.md",
"/pages-data/firefox-theme/",
"/pages-data/firefox-theme/dark-flat-theme-abc.png",
"/pages-data/firefox-theme/dark-flat-theme-abc.zip",
"/pages-data/firefox-theme/index.html",
"/pages-data/firefox-theme/light-flat-theme-abc.png",
"/pages-data/firefox-theme/light-flat-theme-abc.zip",
"/pages-data/geany-theme/README.md",
"/pages-data/geany-theme/",
"/pages-data/geany-theme/abc-dark.conf",
"/pages-data/geany-theme/abc-dark.png",
"/pages-data/geany-theme/abc-light.conf",
"/pages-data/geany-theme/abc-light.png",
"/pages-data/geany-theme/dark.css",
"/pages-data/geany-theme/index.html",
"/pages-data/geany-theme/light.css",
"/pages-data/icons/agree.svg",
"/pages-data/icons/",
"/pages-data/icons/app.svg",
"/pages-data/icons/blocked.svg",
"/pages-data/icons/books.svg",
"/pages-data/icons/bottom-line.svg",
"/pages-data/icons/button.svg",
"/pages-data/icons/calculator.svg",
"/pages-data/icons/camera.svg",
"/pages-data/icons/chart.svg",
"/pages-data/icons/circle.svg",
"/pages-data/icons/clapper-board.svg",
"/pages-data/icons/clock.svg",
"/pages-data/icons/close.svg",
"/pages-data/icons/code.svg",
"/pages-data/icons/dot.svg",
"/pages-data/icons/down-arrow.svg",
"/pages-data/icons/droplet.svg",
"/pages-data/icons/filter.svg",
"/pages-data/icons/folder.svg",
"/pages-data/icons/four-rectangles.svg",
"/pages-data/icons/game.svg",
"/pages-data/icons/gear.svg",
"/pages-data/icons/grid.svg",
"/pages-data/icons/h.svg",
"/pages-data/icons/heart.svg",
"/pages-data/icons/herb.svg",
"/pages-data/icons/hi.svg",
"/pages-data/icons/home.svg",
"/pages-data/icons/icons-data.zip",
"/pages-data/icons/image.svg",
"/pages-data/icons/index.html",
"/pages-data/icons/information.svg",
"/pages-data/icons/inspiration-log.html",
"/pages-data/icons/keyboard.svg",
"/pages-data/icons/left-arrow.svg",
"/pages-data/icons/light-bulb.svg",
"/pages-data/icons/link.svg",
"/pages-data/icons/list.svg",
"/pages-data/icons/live.svg",
"/pages-data/icons/memo.svg",
"/pages-data/icons/menu-open.svg",
"/pages-data/icons/menu.svg",
"/pages-data/icons/movie.svg",
"/pages-data/icons/music.svg",
"/pages-data/icons/navigation.svg",
"/pages-data/icons/new.svg",
"/pages-data/icons/newspaper.svg",
"/pages-data/icons/number.svg",
"/pages-data/icons/page.svg",
"/pages-data/icons/palette.svg",
"/pages-data/icons/paste.svg",
"/pages-data/icons/pencil.svg",
"/pages-data/icons/play.svg",
"/pages-data/icons/plus.svg",
"/pages-data/icons/printer.svg",
"/pages-data/icons/profile.svg",
"/pages-data/icons/progress.svg",
"/pages-data/icons/proportions.svg",
"/pages-data/icons/pushpin.svg",
"/pages-data/icons/question.svg",
"/pages-data/icons/radio.svg",
"/pages-data/icons/redirect-arraw.svg",
"/pages-data/icons/refresh.svg",
"/pages-data/icons/resize.svg",
"/pages-data/icons/right-arrow.svg",
"/pages-data/icons/rss.svg",
"/pages-data/icons/search.svg",
"/pages-data/icons/shuffle.svg",
"/pages-data/icons/sound.svg",
"/pages-data/icons/square.svg",
"/pages-data/icons/star.svg",
"/pages-data/icons/store.svg",
"/pages-data/icons/text.svg",
"/pages-data/icons/textarea.svg",
"/pages-data/icons/three-dots.svg",
"/pages-data/icons/tv.svg",
"/pages-data/icons/up-arrow.svg",
"/pages-data/icons/usb-drive.svg",
"/pages-data/icons/warning.svg",
"/pages-data/icons/weather.svg",
"/pages-data/images/2024/ai-assistant-inkscape-png-62.png",
"/pages-data/images/",
"/pages-data/images/2024/",
"/pages-data/images/2024/app-icon-png-64.png",
"/pages-data/images/2024/art-krita-png-28.png",
"/pages-data/images/2024/ava-woman-laptop-ava-inkscape-svg-12.svg",
"/pages-data/images/2024/ava-woman-laptop-inkscape-svg-30.svg",
"/pages-data/images/2024/barbie-time-inkscape-svg-10.svg",
"/pages-data/images/2024/bg-black-krita-png-39.png",
"/pages-data/images/2024/bg-white-krita-png-38.png",
"/pages-data/images/2024/binary-text-desktop-wallpaper-dark-inkscape-png-26.png",
"/pages-data/images/2024/binary-text-desktop-wallpaper-light-inkscape-png-25.png",
"/pages-data/images/2024/binary-text-mobile-wallpaper-dark-inkscape-png-23.png",
"/pages-data/images/2024/binary-text-mobile-wallpaper-light-inkscape-png-24.png",
"/pages-data/images/2024/building-krita-png-1.png",
"/pages-data/images/2024/circle-dark-wallpaper-desktop-jpg-16.jpg",
"/pages-data/images/2024/circle-light-wallpaper-desktop-jpg-15.jpg",
"/pages-data/images/2024/circle-olive-wallpaper-desktop-jpg-14.jpg",
"/pages-data/images/2024/day-night-inkscape-png-45.png",
"/pages-data/images/2024/day-night-inkscape-svg-56.svg",
"/pages-data/images/2024/editor-code-light-dark-mode-gif-27.gif",
"/pages-data/images/2024/hello-world-big-black-wallpaper-inkscape-png-55.png",
"/pages-data/images/2024/hello-world-big-dark-wallpaper-inkscape-png-51.png",
"/pages-data/images/2024/hello-world-big-dark-wallpaper-inkscape-svg-50.svg",
"/pages-data/images/2024/hello-world-big-light-wallpaper-inkscape-png-53.png",
"/pages-data/images/2024/hello-world-big-light-wallpaper-inkscape-svg-52.svg",
"/pages-data/images/2024/hello-world-big-white-wallpaper-inkscape-png-54.png",
"/pages-data/images/2024/hello-world-binary-black-wallpaper-inkscape-png-48.png",
"/pages-data/images/2024/hello-world-binary-dark-wallpaper-inkscape-svg-46.svg",
"/pages-data/images/2024/hello-world-binary-light-wallpaper-inkscape-svg-47.svg",
"/pages-data/images/2024/hello-world-binary-text-dark-wallpaper--inkscape-png-42.png",
"/pages-data/images/2024/hello-world-binary-text-light-wallpaper-binary-inkscape-png-43.png",
"/pages-data/images/2024/hello-world-binary-white-wallpaper-inkscape-png-49.png",
"/pages-data/images/2024/landscape-dark-blue-wallpaper-desktop-inkscape-jpg-20.jpg",
"/pages-data/images/2024/landscape-dark-blue-wallpaper-mobile-inkscape-jpg-21.jpg",
"/pages-data/images/2024/landscape-inkscape-svg-2.svg",
"/pages-data/images/2024/landscape-light-blue-wallpaper-desktop-inkscape-jpg-19.jpg",
"/pages-data/images/2024/landscape-light-blue-wallpaper-mobile-inkscape-jpg-22.jpg",
"/pages-data/images/2024/logo-circle-oval-inkscape-png-41.png",
"/pages-data/images/2024/logo-circle-oval-inkscape-svg-40.svg",
"/pages-data/images/2024/logo-diamond-inkscape-png-34.png",
"/pages-data/images/2024/logo-t-inkscape-svg-6.svg",
"/pages-data/images/2024/logo-x-inkscape-svg-5.svg",
"/pages-data/images/2024/logo-x-inkscape-svg-7.svg",
"/pages-data/images/2024/logo-x-inkscape-svg-8.svg",
"/pages-data/images/2024/logo-x-inkscape-svg-9.svg",
"/pages-data/images/2024/mail-art-inkscape-svg-31.svg",
"/pages-data/images/2024/music-note-icon-inkscape-svg-44.svg",
"/pages-data/images/2024/one-black-pixel-inkscape-png-35.png",
"/pages-data/images/2024/one-transparent-pixel-inkscape-png-37.png",
"/pages-data/images/2024/one-white-pixel-inkscape-png-36.png",
"/pages-data/images/2024/rss-icon-png-63.png",
"/pages-data/images/2024/search-page-inkscape-png-61.png",
"/pages-data/images/2024/sound-icon-png-65.png",
"/pages-data/images/2024/star-inkscape-svg-4.svg",
"/pages-data/images/2024/start-end-krita-png-0.png",
"/pages-data/images/2024/test-inkscape-png-58.png",
"/pages-data/images/2024/test-inkscape-svg-57.svg",
"/pages-data/images/2024/transparent-background-inkscape-png-29.png",
"/pages-data/images/2024/triangle-dark-wallpaper-desktop-jpg-17.jpg",
"/pages-data/images/2024/triangle-light-wallpaper-desktop-jpg-18.jpg",
"/pages-data/images/2024/web-design-trend-svg-inkscape-svg-11.svg",
"/pages-data/images/2024/website-inkscape-svg-59.svg",
"/pages-data/images/2024/website-inkscape-svg-60.png",
"/pages-data/images/index.html",
"/pages-data/photos/2024/branch-10.jpg",
"/pages-data/photos/",
"/pages-data/photos/2024/",
"/pages-data/photos/2024/branch-9.jpg",
"/pages-data/photos/2024/droplets-and-branch-3.jpg",
"/pages-data/photos/2024/droplets-and-branch-4.jpg",
"/pages-data/photos/2024/droplets-and-branch-5.jpg",
"/pages-data/photos/2024/droplets-branch-7.jpg",
"/pages-data/photos/2024/flower-15.jpg",
"/pages-data/photos/2024/flower-17.jpg",
"/pages-data/photos/2024/flower-2.jpg",
"/pages-data/photos/2024/flower-6.jpg",
"/pages-data/photos/2024/frog-11.jpg",
"/pages-data/photos/index.html",
"/pages-data/templates/about-me-page-auto-light-dark-21/index.html",
"/pages-data/templates/",
"/pages-data/templates/about-me-page-auto-light-dark-21/",
"/pages-data/templates/about-me-page-auto-light-dark-21/style.css",
"/pages-data/templates/card-page-auto-light-dark-20/image.png",
"/pages-data/templates/card-page-auto-light-dark-20/",
"/pages-data/templates/card-page-auto-light-dark-20/index.html",
"/pages-data/templates/card-page-auto-light-dark-20/page.html",
"/pages-data/templates/card-page-auto-light-dark-20/style.css",
"/pages-data/templates/clean-one-page-mini-simple-auto-light-dark-16/index.html",
"/pages-data/templates/clean-one-page-mini-simple-auto-light-dark-16/",
"/pages-data/templates/clean-one-page-mini-simple-auto-light-dark-16/style.css",
"/pages-data/templates/flower-one-page-mini-auto-light-dark-flat-17/flower.svg",
"/pages-data/templates/flower-one-page-mini-auto-light-dark-flat-17/",
"/pages-data/templates/flower-one-page-mini-auto-light-dark-flat-17/index.html",
"/pages-data/templates/flower-one-page-mini-auto-light-dark-flat-17/style.css",
"/pages-data/templates/home-page-auto-light-dark-flat-9/index.html",
"/pages-data/templates/home-page-auto-light-dark-flat-9/",
"/pages-data/templates/home-page-auto-light-dark-flat-9/menu.html",
"/pages-data/templates/home-page-auto-light-dark-flat-9/page.html",
"/pages-data/templates/home-page-auto-light-dark-flat-9/style.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/auto.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/bad.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/d-blue.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/d-forest.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/d-green.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/d-orange.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/d-pink.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/d-plum.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/d-purple.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/d-red.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/d-sea.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/d-slate.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/d-violet.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/d-yellow.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/dark.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/empty.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/h-contrast-d.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/h-contrast-l.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/hight-contrast-dark.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/hight-contrast-light.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/l-blue.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/l-green.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/l-merino.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/l-olive.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/l-orange.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/l-pink.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/l-plum.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/l-purple.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/l-red.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/l-sea.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/l-seashell.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/l-violet.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/l-yellow.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/light.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/o-blue.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/o-green.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/o-lime.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/o-mint.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/o-olive.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/o-orange.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/o-pink.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/o-plum.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/o-purple.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/o-red.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/o-sea.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/o-silver.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/o-violet.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/o-yellow.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/od-blue-2.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/od-blue.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/od-brown.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/od-forest.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/od-gray.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/od-green.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/od-olive.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/od-pink.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/od-plum.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/od-purple.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/od-red.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/od-sea.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/od-slate.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/od-violet.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/od-yellow.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/css/style.css",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/index.html",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/main.js",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/menu.html",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/page.html",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/theme-options.js",
"/pages-data/templates/home-page-flat-auto-many-colors-themes-10/themes.html",
"/pages-data/templates/index.html",
"/pages-data/templates/movie-flat-auto-light-dark-11/index.html",
"/pages-data/templates/movie-flat-auto-light-dark-11/",
"/pages-data/templates/movie-flat-auto-light-dark-11/movie-id.html",
"/pages-data/templates/movie-flat-auto-light-dark-11/movie-poster.png",
"/pages-data/templates/movie-flat-auto-light-dark-11/movie-poster2.png",
"/pages-data/templates/movie-flat-auto-light-dark-11/name.html",
"/pages-data/templates/movie-flat-auto-light-dark-11/search.html",
"/pages-data/templates/movie-flat-auto-light-dark-11/style.css",
"/pages-data/templates/personal-2/index.html",
"/pages-data/templates/personal-2/",
"/pages-data/templates/personal-2/style.css",
"/pages-data/templates/personal-3/index.html",
"/pages-data/templates/personal-3/",
"/pages-data/templates/personal-3/style.css",
"/pages-data/templates/photo-gallery-one-page-flat-auto-light-dark-18/index.html",
"/pages-data/templates/photo-gallery-one-page-flat-auto-light-dark-18/",
"/pages-data/templates/photo-gallery-one-page-flat-auto-light-dark-18/style.css",
"/pages-data/templates/profile-card-flat-mini-auto-light-dark-12/index.html",
"/pages-data/templates/profile-card-flat-mini-auto-light-dark-12/",
"/pages-data/templates/profile-card-flat-mini-auto-light-dark-12/style.css",
"/pages-data/templates/profile-card-mini-flat-auto-light-dark-14/index.html",
"/pages-data/templates/profile-card-mini-flat-auto-light-dark-14/",
"/pages-data/templates/profile-card-mini-flat-auto-light-dark-14/style.css",
"/pages-data/templates/saas-landing-page-auto-light-dark-19/index.html",
"/pages-data/templates/saas-landing-page-auto-light-dark-19/",
"/pages-data/templates/saas-landing-page-auto-light-dark-19/login.html",
"/pages-data/templates/saas-landing-page-auto-light-dark-19/product.png",
"/pages-data/templates/saas-landing-page-auto-light-dark-19/product2.png",
"/pages-data/templates/saas-landing-page-auto-light-dark-19/product3.png",
"/pages-data/templates/saas-landing-page-auto-light-dark-19/product4.png",
"/pages-data/templates/saas-landing-page-auto-light-dark-19/style (copy 1).css",
"/pages-data/templates/saas-landing-page-auto-light-dark-19/style.css",
"/pages-data/templates/simple-4/index.html",
"/pages-data/templates/simple-4/",
"/pages-data/templates/simple-4/style.css",
"/pages-data/templates/simple-5/index.html",
"/pages-data/templates/simple-5/",
"/pages-data/templates/simple-5/style.css",
"/pages-data/templates/simple-6/index.html",
"/pages-data/templates/simple-6/",
"/pages-data/templates/simple-6/style.css",
"/pages-data/templates/simple-7/index.html",
"/pages-data/templates/simple-7/",
"/pages-data/templates/simple-7/style.css",
"/pages-data/templates/simple-8/index.html",
"/pages-data/templates/simple-8/",
"/pages-data/templates/simple-8/style.css",
"/pages-data/templates/simple-text-1/index.html",
"/pages-data/templates/simple-text-1/",
"/pages-data/templates/simple-text-1/style.css",
"/pages-data/templates/tpl-0/index.html",
"/pages-data/templates/tpl-0/",
"/pages-data/templates/tpl-0/style.css",
"/pages-data/templates/web-design-services-simple-auto-light-dark-22/index.html",
"/pages-data/templates/web-design-services-simple-auto-light-dark-22/",
"/pages-data/templates/web-design-services-simple-auto-light-dark-22/style.css",
"/pages-data/templates/webdesign-one-page-mini-flat-auto-light-dark-15/circle.svg",
"/pages-data/templates/webdesign-one-page-mini-flat-auto-light-dark-15/",
"/pages-data/templates/webdesign-one-page-mini-flat-auto-light-dark-15/coffee.svg",
"/pages-data/templates/webdesign-one-page-mini-flat-auto-light-dark-15/index.html",
"/pages-data/templates/webdesign-one-page-mini-flat-auto-light-dark-15/style.css",
"/pages-data/templates/wordpress-theme-home-auto-light-dark-23/screenshot.png",
"/pages-data/templates/wordpress-theme-home-auto-light-dark-23/",
"/pages-data/templates/wordpress-theme-home-auto-light-dark-23/themehome.zip",
"/pages-list.html",
"/projects/agi-countdown-59/data-list.html",
"/projects/",
"/projects/agi-countdown-59/",
"/projects/agi-countdown-59/index.html",
"/projects/agi-countdown-59/script.js",
"/projects/agi-countdown-59/style.css",
"/projects/average-number-40/index.html",
"/projects/average-number-40/",
"/projects/average-number-40/script.js",
"/projects/average-number-40/style.css",
"/projects/background-colors-list-50/index.html",
"/projects/background-colors-list-50/",
"/projects/background-colors-list-50/script.js",
"/projects/background-colors-list-50/style.css",
"/projects/browser-info-test-js-2/index.html",
"/projects/browser-info-test-js-2/",
"/projects/browser-info-test-js-2/script.js",
"/projects/browser-info-test-js-2/style.css",
"/projects/calculator-3/index.html",
"/projects/calculator-3/",
"/projects/calculator-3/script.js",
"/projects/calculator-3/style.css",
"/projects/color-picker-4/index.html",
"/projects/color-picker-4/",
"/projects/color-picker-4/script.js",
"/projects/color-picker-4/style.css",
"/projects/count-symbol-39/index.html",
"/projects/count-symbol-39/",
"/projects/count-symbol-39/script.js",
"/projects/count-symbol-39/style.css",
"/projects/demo-test-style-class-5/index.html",
"/projects/demo-test-style-class-5/",
"/projects/demo-test-style-class-5/script.js",
"/projects/demo-test-style-class-5/style.css",
"/projects/demo-test-style-ui-60/index.html",
"/projects/demo-test-style-ui-60/",
"/projects/demo-test-style-ui-60/script.js",
"/projects/demo-test-style-ui-60/style.css",
"/projects/drawing-7/index.html",
"/projects/drawing-7/",
"/projects/drawing-7/script.js",
"/projects/drawing-7/style.css",
"/projects/google-programmable-search-49/clean.html",
"/projects/google-programmable-search-49/",
"/projects/google-programmable-search-49/index.html",
"/projects/google-programmable-search-49/readme.txt",
"/projects/google-programmable-search-49/script.js",
"/projects/google-programmable-search-49/style.css",
"/projects/google-trends-46/index.html",
"/projects/google-trends-46/",
"/projects/google-trends-46/script.js",
"/projects/google-trends-46/style.css",
"/projects/highlight-word-15/index.html",
"/projects/highlight-word-15/",
"/projects/highlight-word-15/script.js",
"/projects/highlight-word-15/style.css",
"/projects/index.html",
"/projects/insert-icon-17/demo.js",
"/projects/insert-icon-17/",
"/projects/insert-icon-17/index.html",
"/projects/insert-icon-17/old-emoji-script (copy 1).js",
"/projects/insert-icon-17/old-material-icon-script.js",
"/projects/insert-icon-17/script.js",
"/projects/insert-icon-17/style.css",
"/projects/keep-1/index.html",
"/projects/keep-1/",
"/projects/keep-1/script.js",
"/projects/keep-1/style.css",
"/projects/lag-test-47/index.html",
"/projects/lag-test-47/",
"/projects/lag-test-47/script.js",
"/projects/lag-test-47/style.css",
"/projects/movie-list-19/index.html",
"/projects/movie-list-19/",
"/projects/movie-list-19/script (copy 1).js",
"/projects/movie-list-19/script.js",
"/projects/movie-list-19/style.css",
"/projects/music-20/index.html",
"/projects/music-20/",
"/projects/music-20/script.js",
"/projects/music-20/style.css",
"/projects/music-blog-72/index.html",
"/projects/music-blog-72/",
"/projects/music-blog-72/script.js",
"/projects/music-blog-72/style.css",
"/projects/navigation-71/demo.js",
"/projects/navigation-71/",
"/projects/navigation-71/index.html",
"/projects/navigation-71/noscript.css",
"/projects/navigation-71/script.js",
"/projects/navigation-71/style.css",
"/projects/podcast-70/index.html",
"/projects/podcast-70/",
"/projects/podcast-70/script.js",
"/projects/podcast-70/style.css",
"/projects/print-53/index.html",
"/projects/print-53/",
"/projects/print-53/script.js",
"/projects/print-53/style.css",
"/projects/radio-22/index.html",
"/projects/radio-22/",
"/projects/radio-22/script.js",
"/projects/radio-22/style.css",
"/projects/rain-38/index.html",
"/projects/rain-38/",
"/projects/rain-38/script.js",
"/projects/rain-38/style.css",
"/projects/random-color-generator-51/demo.js",
"/projects/random-color-generator-51/",
"/projects/random-color-generator-51/index.html",
"/projects/random-color-generator-51/script.js",
"/projects/random-color-generator-51/style.css",
"/projects/random-symbol-23/index.html",
"/projects/random-symbol-23/",
"/projects/random-symbol-23/script.js",
"/projects/random-symbol-23/style.css",
"/projects/random-text-generator-24/index.html",
"/projects/random-text-generator-24/",
"/projects/random-text-generator-24/script.js",
"/projects/random-text-generator-24/style.css",
"/projects/random-website-69/data-list.html",
"/projects/random-website-69/",
"/projects/random-website-69/index.html",
"/projects/random-website-69/script.js",
"/projects/random-website-69/style.css",
"/projects/redirects-25/index.html",
"/projects/redirects-25/",
"/projects/redirects-25/script.js",
"/projects/redirects-25/style.css",
"/projects/remove-duplicates-61/index.html",
"/projects/remove-duplicates-61/",
"/projects/remove-duplicates-61/script.js",
"/projects/remove-duplicates-61/style.css",
"/projects/scroll-effect-when-scroll-48/index.html",
"/projects/scroll-effect-when-scroll-48/",
"/projects/scroll-effect-when-scroll-48/script.js",
"/projects/scroll-effect-when-scroll-48/style.css",
"/projects/sorting-55/index.html",
"/projects/sorting-55/",
"/projects/sorting-55/script.js",
"/projects/sorting-55/style.css",
"/projects/speech-to-text-63/index.html",
"/projects/speech-to-text-63/",
"/projects/speech-to-text-63/script.js",
"/projects/speech-to-text-63/style.css",
"/projects/speed-dial-58/index.html",
"/projects/speed-dial-58/",
"/projects/speed-dial-58/script.js",
"/projects/speed-dial-58/style.css",
"/projects/start-page-41/index.html",
"/projects/start-page-41/",
"/projects/start-page-41/script.js",
"/projects/start-page-41/style.css",
"/projects/test-27/README.md",
"/projects/test-27/",
"/projects/test-27/cursor-hl.png",
"/projects/test-27/cursor-hl.psd",
"/projects/test-27/index.html",
"/projects/test-27/manifest.webmanifest",
"/projects/test-27/screenshot.png",
"/projects/test-27/script.js",
"/projects/test-27/style.css",
"/projects/test-27/sw.js",
"/projects/text-to-binary-52/index.html",
"/projects/text-to-binary-52/",
"/projects/text-to-binary-52/script.js",
"/projects/text-to-binary-52/style.css",
"/projects/text-to-speech/index.html",
"/projects/text-to-speech/",
"/projects/text-to-speech/script.js",
"/projects/text-to-speech/style.css",
"/projects/text-to-url-43/index.html",
"/projects/text-to-url-43/",
"/projects/text-to-url-43/script.js",
"/projects/text-to-url-43/style.css",
"/projects/time-binary-clock-28/index.html",
"/projects/time-binary-clock-28/",
"/projects/time-binary-clock-28/script.js",
"/projects/time-binary-clock-28/style.css",
"/projects/time-clock-29/index.html",
"/projects/time-clock-29/",
"/projects/time-clock-29/script.js",
"/projects/time-clock-29/style.css",
"/projects/time-stopwatch-30/index.html",
"/projects/time-stopwatch-30/",
"/projects/time-stopwatch-30/script.js",
"/projects/time-stopwatch-30/style.css",
"/projects/time-utc-clock-56/index.html",
"/projects/time-utc-clock-56/",
"/projects/time-utc-clock-56/script.js",
"/projects/time-utc-clock-56/style.css",
"/projects/todo-list-31/index.html",
"/projects/todo-list-31/",
"/projects/todo-list-31/script.js",
"/projects/todo-list-31/style.css",
"/projects/todo-list-ideas-32/index.html",
"/projects/todo-list-ideas-32/",
"/projects/todo-list-ideas-32/script.js",
"/projects/todo-list-ideas-32/style.css",
"/projects/tpl-projects-33/index.html",
"/projects/tpl-projects-33/",
"/projects/tpl-projects-33/script.js",
"/projects/tpl-projects-33/style.css",
"/projects/tpl-projects-app-34/README.md",
"/projects/tpl-projects-app-34/",
"/projects/tpl-projects-app-34/index.html",
"/projects/tpl-projects-app-34/manifest.webmanifest",
"/projects/tpl-projects-app-34/screenshot.png",
"/projects/tpl-projects-app-34/script.js",
"/projects/tpl-projects-app-34/style.css",
"/projects/tpl-projects-app-34/sw.js",
"/projects/transliterate-35/index.html",
"/projects/transliterate-35/",
"/projects/transliterate-35/script.js",
"/projects/transliterate-35/style.css",
"/projects/tv-36/index.html",
"/projects/tv-36/",
"/projects/tv-36/script.js",
"/projects/tv-36/style.css",
"/projects/video-18/index.html",
"/projects/video-18/",
"/projects/video-18/script.js",
"/projects/video-18/style.css",
"/projects/weather-37/index.html",
"/projects/weather-37/",
"/projects/weather-37/script.js",
"/projects/weather-37/style.css",
"/projects-group-list.html",
"/projects-list.html",
"/robots.txt",
"/rss.xml",
"/sitemap.xml",
"/sw.js",
"/video/video.mp4",
"/video/",
"/",];
fileListArr.push("no_exit_file_name_for_test.hmtl");

//https://stackoverflow.com/questions/9229645/remove-duplicate-values-from-js-array
fileListArr = [...new Set(fileListArr)]; 




fileListArr.forEach((file) => {
//https://stackoverflow.com/questions/68595209/js-fetch-check-if-file-present-without-downloading-content

//file = '/' + file;

//rm ext
var newFile = hideLinkExt(file);



// with ext
fetch(
file, { method: "HEAD" }
)
.then((res) => {
if (res.ok) {
// file is present at URL
console.log('try cache.add ' + file);
//https://web.dev/learn/pwa/caching/
caches.open("v.1.2.2024.10.26")
.then(cache => {
cache.add(file); // it stores only one resource
//  cache.addAll(["styles.css", "app.js"]); // it stores two resources
});
} else {
console.log('404 not found ' + file);
// file is not present at URL
}
})
.catch((error) => {
  console.log(error)
});


if(file != newFile){

// no ext
fetch(
newFile, { method: "HEAD" }
)
.then((res) => {
if (res.ok) {
// file is present at URL
console.log('try cache.add ' + newFile);
//https://web.dev/learn/pwa/caching/
caches.open("v.1.2.2024.10.26")
.then(cache => {
cache.add(newFile); // it stores only one resource
//  cache.addAll(["styles.css", "app.js"]); // it stores two resources
});
} else {
console.log('404 not found ' + newFile);
// file is not present at URL
}
})
.catch((error) => {
  console.log(error)
});

}




});



});

}




// rm old cache
//https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage/delete
this.addEventListener("activate", (event) => {
  const cachesToKeep = ["v.1.2.2024.10.26"];

  event.waitUntil(
    caches.keys().then((keyList) =>
      Promise.all(
        keyList.map((key) => {
          if (!cachesToKeep.includes(key)) {
            return caches.delete(key);
          }
        }),
      ),
    ),
  );
});




// read cache
/*
//https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#basic_architecture
const cacheFirst = async (request) => {
  const responseFromCache = await caches.match(request, {ignoreSearch: true});
  if (responseFromCache) {
    return responseFromCache;
  }
return fetch(request);
};

self.addEventListener("fetch", (event) => {
  event.respondWith(cacheFirst(event.request));
});*/




/*//https://web.dev/learn/pwa/serving
// cache first
self.addEventListener("fetch", event => {
   event.respondWith(
     caches.match(event.request, {ignoreSearch: true})
     .then(cachedResponse => {
       // It can update the cache to serve updated content on the next request
         return cachedResponse || fetch(event.request);
     }
   )
  )
});*/


//https://web.dev/learn/pwa/serving
// cache first
self.addEventListener("fetch", event => {
   event.respondWith(
     caches.match(event.request, {ignoreSearch: true})
     .then(cachedResponse => {
       // It can update the cache to serve updated content on the next request
         return cachedResponse || fetch(event.request);
     }
   )
  )
});

// read cache


