
//var myCacheVersion = "v.1.2.2024.03.20";






//https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#basic_architecture
const registerServiceWorker = async () => {
  if ("serviceWorker" in navigator) {
    try {
      const registration = await navigator.serviceWorker.register("/sw.js", {
        scope: "/",
      });
      if (registration.installing) {
        console.log("Service worker installing");
      } else if (registration.waiting) {
        console.log("Service worker installed");
  
    } else if (registration.active) {



}
    } catch (error) {

console.error(`Registration failed with ` + error);
    }
  }
};



registerServiceWorker();
swJsInstallFiles();



// fu hide file extension
function hideLinkExt(url){
var linkExtList = ["index.html", ".html"];
var newURL = url;

linkExtList.forEach((element) => {
newURL = newURL.replace(element, '');
});

return newURL;
}
//














function swJsInstallFiles(){

/*
// cache
//https://stackoverflow.com/questions/66529102/uncaught-in-promise-typeerror-failed-to-execute-cache-on-addall-request
//https://github.com/mdn/pwa-examples
self.addEventListener('install', (e) => {
e.waitUntil(caches.open("v.1.2.2024.03.20").then((cache) => cache.addAll(fileListArrFound)),);
});*/






// cache
//https://developer.mozilla.org/en-US/docs/Web/API/Cache/addAll

self.addEventListener('install', (e) => {


// start check 404, file list 2
var fileListArr = ["/404.html",
"/BingSiteAuth.xml",
"/LICENSE.md",
"/README.md",
"/about.html",
"/ads.html",
"/archive/disqus-60/index.html",
"/archive/",
"/archive/disqus-60/",
"/archive/disqus-60/script.js",
"/archive/disqus-60/style.css",
"/archive/dropdown-menu-8/index.html",
"/archive/dropdown-menu-8/",
"/archive/dropdown-menu-8/script.js",
"/archive/dropdown-menu-8/style.css",
"/archive/index.html",
"/archive/not-sleep-pc-12/index.html",
"/archive/not-sleep-pc-12/",
"/archive/not-sleep-pc-12/style.css",
"/archive-list.html",
"/audio/click.mp3",
"/audio/",
"/audio/click2.mp3",
"/audio/error.mp3",
"/audio/game-over.mp3",
"/audio/neutral.mp3",
"/audio/ok.mp3",
"/audio/win.mp3",
"/blog.html",
"/changelog.html",
"/chrome-extensions/README.md",
"/chrome-extensions/",
"/chrome-extensions/badge-count-up-timer-4/background.js",
"/chrome-extensions/badge-count-up-timer-4/",
"/chrome-extensions/badge-count-up-timer-4/icon512x512.png",
"/chrome-extensions/badge-count-up-timer-4/icon512x512.svg",
"/chrome-extensions/badge-count-up-timer-4/manifest.json",
"/chrome-extensions/badge-count-up-timer-4/popup.html",
"/chrome-extensions/badge-count-up-timer-4/script.js",
"/chrome-extensions/badge-count-up-timer-4.crx",
"/chrome-extensions/hotkey-url-5/README.md",
"/chrome-extensions/hotkey-url-5/",
"/chrome-extensions/hotkey-url-5/icon512x512.png",
"/chrome-extensions/hotkey-url-5/icon512x512.svg",
"/chrome-extensions/hotkey-url-5/light.css",
"/chrome-extensions/hotkey-url-5/main.css",
"/chrome-extensions/hotkey-url-5/manifest.json",
"/chrome-extensions/hotkey-url-5/options.html",
"/chrome-extensions/hotkey-url-5/options.js",
"/chrome-extensions/hotkey-url-5/screenshot.png",
"/chrome-extensions/hotkey-url-5/script.js",
"/chrome-extensions/hotkey-url-5/style-main.css",
"/chrome-extensions/hotkey-url-5/style.css",
"/chrome-extensions/hotkey-url-5/worker.js",
"/chrome-extensions/hotkey-url-5.crx",
"/chrome-extensions/index.html",
"/chrome-extensions/new-tab-redirect-3/README.md",
"/chrome-extensions/new-tab-redirect-3/",
"/chrome-extensions/new-tab-redirect-3/icon512x512.png",
"/chrome-extensions/new-tab-redirect-3/icon512x512.svg",
"/chrome-extensions/new-tab-redirect-3/light.css",
"/chrome-extensions/new-tab-redirect-3/main.css",
"/chrome-extensions/new-tab-redirect-3/manifest.json",
"/chrome-extensions/new-tab-redirect-3/new-tab-redirect.html",
"/chrome-extensions/new-tab-redirect-3/options.html",
"/chrome-extensions/new-tab-redirect-3/options.js",
"/chrome-extensions/new-tab-redirect-3/screenshot.png",
"/chrome-extensions/new-tab-redirect-3/screenshot2.png",
"/chrome-extensions/new-tab-redirect-3/script.js",
"/chrome-extensions/new-tab-redirect-3/style.css",
"/chrome-extensions/new-tab-redirect-3.crx",
"/chrome-extensions-page.html",
"/chrome-theme/License-and-source.txt",
"/chrome-theme/",
"/chrome-theme/dark-theme/manifest.json",
"/chrome-theme/dark-theme/",
"/chrome-theme/dark-theme.crx",
"/chrome-theme/dark-theme.png",
"/chrome-theme/index.html",
"/chrome-theme/light-theme/manifest.json",
"/chrome-theme/light-theme/",
"/chrome-theme/light-theme.crx",
"/chrome-theme/light-theme.png",
"/chrome-theme/tpl-theme/manifest.json",
"/chrome-theme/tpl-theme/",
"/chrome-theme-page.html",
"/css/a-backup-old.css",
"/css/",
"/css/auto.css",
"/css/d-blue.css",
"/css/d-green.css",
"/css/d-orange.css",
"/css/d-pink.css",
"/css/d-plum.css",
"/css/d-purple.css",
"/css/d-red.css",
"/css/d-sea.css",
"/css/d-violet.css",
"/css/d-yellow.css",
"/css/dark.css",
"/css/empty.css",
"/css/h-contrast-d.css",
"/css/h-contrast-l.css",
"/css/l-blue.css",
"/css/l-green.css",
"/css/l-olive.css",
"/css/l-orange.css",
"/css/l-pink.css",
"/css/l-plum.css",
"/css/l-purple.css",
"/css/l-red.css",
"/css/l-sea.css",
"/css/l-seashell.css",
"/css/l-violet.css",
"/css/l-yellow.css",
"/css/light.css",
"/css/main.css",
"/css/noscript.css",
"/css/o-blue.css",
"/css/o-green.css",
"/css/o-lime.css",
"/css/o-mint.css",
"/css/o-olive.css",
"/css/o-orange.css",
"/css/o-pink.css",
"/css/o-plum.css",
"/css/o-purple.css",
"/css/o-sea.css",
"/css/o-silver.css",
"/css/o-violet.css",
"/css/o-yellow.css",
"/css/od-blue.css",
"/css/od-brown.css",
"/css/od-forest.css",
"/css/od-gray.css",
"/css/od-green.css",
"/css/od-olive.css",
"/css/od-pink.css",
"/css/od-plum.css",
"/css/od-purple.css",
"/css/od-red.css",
"/css/od-sea.css",
"/css/od-slate.css",
"/css/od-violet.css",
"/css/od-yellow.css",
"/css/rss.css",
"/css/style.css",
"/css-art/computer-css-9/index.html",
"/css-art/",
"/css-art/computer-css-9/",
"/css-art/computer-css-9/style.css",
"/css-art/index.html",
"/css-art/pumpkin-css-15/index.html",
"/css-art/pumpkin-css-15/",
"/css-art/pumpkin-css-15/style.css",
"/css-art/realistic-old-windows-os-popup-window-12/index.html",
"/css-art/realistic-old-windows-os-popup-window-12/",
"/css-art/realistic-old-windows-os-popup-window-12/style.css",
"/css-art/tpl-0/index.html",
"/css-art/tpl-0/",
"/css-art/tpl-0/style.css",
"/css-art/woman-css-32/index.html",
"/css-art/woman-css-32/",
"/css-art/woman-css-32/style.css",
"/css-art-page.html",
"/data/adsJsonVar.js",
"/data/",
"/data/agicountdownJsonVar.js",
"/data/articlesJsonVar.js",
"/data/blogJsonVar.js",
"/data/bookJsonVar.js",
"/data/bookmarksJsonVar.js",
"/data/iconsJsonVar.js",
"/data/musicJsonVar.js",
"/data/quizJsonVar.js",
"/data/quoteJsonVar.js",
"/data/radioJsonVar.js",
"/data/sitemapJsonVar.js",
"/data/tvJsonVar.js",
"/data/videoJsonVar.js",
"/data/wordJsonVar.js",
"/data-other/img/close10x10.png",
"/data-other/",
"/data-other/img/",
"/data-other/img/close10x10.psd",
"/data-other-page.html",
"/data-page.html",
"/data2/WATCHLIST.csv",
"/data2/",
"/data2-page.html",
"/favicon.ico",
"/firefox-extensions/badge-count-up-timer-4/4-firefox-badge-count-up-timer-extension.zip",
"/firefox-extensions/",
"/firefox-extensions/badge-count-up-timer-4/",
"/firefox-extensions/badge-count-up-timer-4/README.md",
"/firefox-extensions/badge-count-up-timer-4/background.html",
"/firefox-extensions/badge-count-up-timer-4/background.js",
"/firefox-extensions/badge-count-up-timer-4/icon512x512.png",
"/firefox-extensions/badge-count-up-timer-4/icon512x512.svg",
"/firefox-extensions/badge-count-up-timer-4/light.css",
"/firefox-extensions/badge-count-up-timer-4/manifest.json",
"/firefox-extensions/badge-count-up-timer-4/popup.html",
"/firefox-extensions/badge-count-up-timer-4/screenshot.png",
"/firefox-extensions/badge-count-up-timer-4/script.js",
"/firefox-extensions/badge-count-up-timer-4/style-main.css",
"/firefox-extensions/badge-count-up-timer-4/style.css",
"/firefox-extensions/hotkey-url-5/README.md",
"/firefox-extensions/hotkey-url-5/",
"/firefox-extensions/hotkey-url-5/hotkey-url-5.zip",
"/firefox-extensions/hotkey-url-5/icon512x512.png",
"/firefox-extensions/hotkey-url-5/icon512x512.svg",
"/firefox-extensions/hotkey-url-5/main.css",
"/firefox-extensions/hotkey-url-5/manifest.json",
"/firefox-extensions/hotkey-url-5/options.html",
"/firefox-extensions/hotkey-url-5/options.js",
"/firefox-extensions/hotkey-url-5/screenshot.png",
"/firefox-extensions/hotkey-url-5/script.js",
"/firefox-extensions/hotkey-url-5/style.css",
"/firefox-extensions/hotkey-url-5/worker.js",
"/firefox-extensions/index.html",
"/firefox-extensions/new-tab-redirect-3/README.md",
"/firefox-extensions/new-tab-redirect-3/",
"/firefox-extensions/new-tab-redirect-3/icon512x512.png",
"/firefox-extensions/new-tab-redirect-3/icon512x512.svg",
"/firefox-extensions/new-tab-redirect-3/main.css",
"/firefox-extensions/new-tab-redirect-3/manifest.json",
"/firefox-extensions/new-tab-redirect-3/new-tab-redirect-3.zip",
"/firefox-extensions/new-tab-redirect-3/new-tab-redirect.html",
"/firefox-extensions/new-tab-redirect-3/options.html",
"/firefox-extensions/new-tab-redirect-3/options.js",
"/firefox-extensions/new-tab-redirect-3/screenshot.png",
"/firefox-extensions/new-tab-redirect-3/screenshot2.png",
"/firefox-extensions/new-tab-redirect-3/screenshot3.png",
"/firefox-extensions/new-tab-redirect-3/script.js",
"/firefox-extensions/new-tab-redirect-3/style.css",
"/firefox-extensions/search-localhost-http-1/icon512x512.png",
"/firefox-extensions/search-localhost-http-1/",
"/firefox-extensions/search-localhost-http-1/icon512x512.svg",
"/firefox-extensions/search-localhost-http-1/manifest.json",
"/firefox-extensions/search-localhost-http-1/search-localhost-http-1.zip",
"/firefox-extensions/search-localhost-https-2/icon512x512.png",
"/firefox-extensions/search-localhost-https-2/",
"/firefox-extensions/search-localhost-https-2/icon512x512.svg",
"/firefox-extensions/search-localhost-https-2/manifest.json",
"/firefox-extensions/search-localhost-https-2/search-localhost-https-2.zip",
"/firefox-extensions/url-redirect-6/README.md",
"/firefox-extensions/url-redirect-6/",
"/firefox-extensions/url-redirect-6/icon512x512.png",
"/firefox-extensions/url-redirect-6/icon512x512.svg",
"/firefox-extensions/url-redirect-6/main.css",
"/firefox-extensions/url-redirect-6/manifest.json",
"/firefox-extensions/url-redirect-6/options.html",
"/firefox-extensions/url-redirect-6/options.js",
"/firefox-extensions/url-redirect-6/screenshot.png",
"/firefox-extensions/url-redirect-6/script.js",
"/firefox-extensions/url-redirect-6/style.css",
"/firefox-extensions/url-redirect-6/url-redirect-6.zip",
"/firefox-extensions-page.html",
"/firefox-theme/README.md",
"/firefox-theme/",
"/firefox-theme/dark-flat-theme-abc.png",
"/firefox-theme/dark-flat-theme-abc.zip",
"/firefox-theme/index.html",
"/firefox-theme/light-flat-theme-abc.png",
"/firefox-theme/light-flat-theme-abc.zip",
"/firefox-theme-page.html",
"/geany-theme/README.md",
"/geany-theme/",
"/geany-theme/abc-dark.conf",
"/geany-theme/abc-dark.png",
"/geany-theme/abc-light.conf",
"/geany-theme/abc-light.png",
"/geany-theme/dark.css",
"/geany-theme/default.conf",
"/geany-theme/index.html",
"/geany-theme/light.css",
"/geany-theme-page.html",
"/googlebae648489b2c26df.html",
"/icons-data/books.svg",
"/icons-data/",
"/icons-data/bottom-line.svg",
"/icons-data/button.svg",
"/icons-data/calculator.svg",
"/icons-data/camera.svg",
"/icons-data/chart.svg",
"/icons-data/circle.svg",
"/icons-data/clapper-board.svg",
"/icons-data/clock.svg",
"/icons-data/code.svg",
"/icons-data/dot.svg",
"/icons-data/droplet.svg",
"/icons-data/folder.svg",
"/icons-data/game.svg",
"/icons-data/gear.svg",
"/icons-data/grid.svg",
"/icons-data/heart.svg",
"/icons-data/herb.svg",
"/icons-data/hi.svg",
"/icons-data/image.svg",
"/icons-data/index.html",
"/icons-data/information.svg",
"/icons-data/inspiration-log.html",
"/icons-data/keyboard.svg",
"/icons-data/light-bulb.svg",
"/icons-data/link.svg",
"/icons-data/live.svg",
"/icons-data/memo.svg",
"/icons-data/movie.svg",
"/icons-data/music.svg",
"/icons-data/navigation.svg",
"/icons-data/new.svg",
"/icons-data/number.svg",
"/icons-data/page.svg",
"/icons-data/palette.svg",
"/icons-data/paste.svg",
"/icons-data/pencil.svg",
"/icons-data/play.svg",
"/icons-data/printer.svg",
"/icons-data/profile.svg",
"/icons-data/progress.svg",
"/icons-data/proportions.svg",
"/icons-data/pushpin.svg",
"/icons-data/radio.svg",
"/icons-data/redirect-arraw.svg",
"/icons-data/refresh.svg",
"/icons-data/resize.svg",
"/icons-data/search.svg",
"/icons-data/shuffle.svg",
"/icons-data/square.svg",
"/icons-data/star.svg",
"/icons-data/store.svg",
"/icons-data/text.svg",
"/icons-data/textarea.svg",
"/icons-data/three-dots.svg",
"/icons-data/tv.svg",
"/icons-data/usb-drive.svg",
"/icons-data/warning.svg",
"/icons-data/weather.svg",
"/icons-page.html",
"/images/0-100/art-krita-28.png",
"/images/",
"/images/0-100/",
"/images/0-100/ava-woman-laptop-ava-inkscape-svg-12.svg",
"/images/0-100/ava-woman-laptop-inkscape-svg-30.svg",
"/images/0-100/barbie-time-inkscape-svg-10.svg",
"/images/0-100/bg-black-png-krita-39.png",
"/images/0-100/bg-white-png-krita-38.png",
"/images/0-100/binary-text-desktop-wallpaper-dark-inkscape-png-26.png",
"/images/0-100/binary-text-desktop-wallpaper-light-inkscape-png-25.png",
"/images/0-100/binary-text-mobile-wallpaper-dark-inkscape-png-23.png",
"/images/0-100/binary-text-mobile-wallpaper-light-inkscape-png-24.png",
"/images/0-100/building-krita-png-1.png",
"/images/0-100/circle-dark-wallpaper-desktop-jpg-16.jpg",
"/images/0-100/circle-light-wallpaper-desktop-jpg-15.jpg",
"/images/0-100/circle-olive-wallpaper-desktop-jpg-14.jpg",
"/images/0-100/day-night-inkscape-png-45.png",
"/images/0-100/day-night-inkscape-svg-45.svg",
"/images/0-100/editor-code-light-dark-mode-gif-27.gif",
"/images/0-100/hello-world-big-black-wallpaper-inkscape-svg-55.png",
"/images/0-100/hello-world-big-dark-wallpaper-inkscape-png-51.png",
"/images/0-100/hello-world-big-dark-wallpaper-inkscape-svg-50.svg",
"/images/0-100/hello-world-big-light-wallpaper-inkscape-png-53.png",
"/images/0-100/hello-world-big-light-wallpaper-inkscape-svg-52.svg",
"/images/0-100/hello-world-big-white-wallpaper-inkscape-png-54.png",
"/images/0-100/hello-world-binary-black-wallpaper-inkscape-png-48.png",
"/images/0-100/hello-world-binary-dark-wallpaper-inkscape-svg-46.svg",
"/images/0-100/hello-world-binary-light-wallpaper-inkscape-svg-47.svg",
"/images/0-100/hello-world-binary-text-dark-wallpaper--inkscape-png-42.png",
"/images/0-100/hello-world-binary-text-light-wallpaper-binary-inkscape-png-43.png",
"/images/0-100/hello-world-binary-white-wallpaper-inkscape-png-49.png",
"/images/0-100/landscape-dark-blue-wallpaper-desktop-inkscape-jpg-20.jpg",
"/images/0-100/landscape-dark-blue-wallpaper-mobile-inkscape-jpg-21.jpg",
"/images/0-100/landscape-inkscape-svg-2.svg",
"/images/0-100/landscape-light-blue-wallpaper-desktop-inkscape-jpg-19.jpg",
"/images/0-100/landscape-light-blue-wallpaper-mobile-inkscape-jpg-22.jpg",
"/images/0-100/logo-circle-oval-png-inkscape-41.png",
"/images/0-100/logo-circle-oval-svg-inkscape-40.svg",
"/images/0-100/logo-diamond-inkscape-png-34.png",
"/images/0-100/logo-t-inkscape-svg-6.svg",
"/images/0-100/logo-x-inkscape-svg-5.svg",
"/images/0-100/logo-x-inkscape-svg-7.svg",
"/images/0-100/logo-x-inkscape-svg-8.svg",
"/images/0-100/logo-x-inkscape-svg-9.svg",
"/images/0-100/mail-art-inkscape-31.svg",
"/images/0-100/music-note-icon-inkscape-svg-44.svg",
"/images/0-100/one-black-pixel-png-inkscape-35.png",
"/images/0-100/one-transparent-pixel-png-inkscape-37.png",
"/images/0-100/one-white-pixel-png-inkscape-36.png",
"/images/0-100/star-inkscape-svg-4.svg",
"/images/0-100/start-end-krita-png-0.png",
"/images/0-100/transparent-background-inkscape-29.png",
"/images/0-100/triangle-dark-wallpaper-desktop-jpg-17.jpg",
"/images/0-100/triangle-light-wallpaper-desktop-jpg-18.jpg",
"/images/0-100/web-design-trend-svg-inkscape-svg-11.svg",
"/images/index.html",
"/images-page.html",
"/img/404.png",
"/img/",
"/img/404.svg",
"/img/bg-dark.svg",
"/img/bg-light.svg",
"/img/favicon16x16.png",
"/img/github-banner-settings.png",
"/img/github-banner-settings.svg",
"/img/header-banner (copy 1).svg",
"/img/header-banner.png",
"/img/header-banner.svg",
"/img/logo (copy 1).svg",
"/img/logo.jpeg",
"/img/logo.png",
"/img/logo.svg",
"/img/maskable_logo.png",
"/img/other/art.png",
"/img/other/",
"/img/repository-open-graph-template.png",
"/img/screenshots/dark.png",
"/img/screenshots/",
"/img/screenshots/firefox-dark.png",
"/img/screenshots/firefox-light.png",
"/img/screenshots/geany-dark.png",
"/img/screenshots/geany-light.png",
"/img/screenshots/icons.png",
"/img/screenshots/light.png",
"/img/screenshots/theme-option.png",
"/img/screenshots/todo.png",
"/img/screenshots/typing.png",
"/img/tpl/ava.png",
"/img/tpl/",
"/img/tpl/ava.svg",
"/img/tpl/bg-dark.png",
"/img/tpl/bg-light.png",
"/img/tpl/favicon.ico",
"/img/tpl/favicon.png",
"/img/tpl/flower.png",
"/img/tpl/flower.svg",
"/img/tpl/header-banner.svg",
"/img/tpl/image.png",
"/img/tpl/logo.png",
"/img/tpl/logo.svg",
"/img/tpl/logo2.png",
"/img/tpl/logo2.svg",
"/img/tpl/photo.jpg",
"/img/tpl/photo2.jpg",
"/img/tpl/tree.svg",
"/img/tpl/woman.png",
"/img/tpl/woman.svg",
"/img/transparent.png",
"/img/transparent.svg",
"/index.html",
"/install.html",
"/js/ad.js",
"/js/",
"/js/backup.txt",
"/js/cookieAgreePopup.js",
"/js/fuPostTime.js",
"/js/main.js",
"/js/script.js",
"/js/settings-options.js",
"/js/theme-options.js",
"/links.html",
"/lists.html",
"/main-list.html",
"/manifest.webmanifest",
"/mini-projects/animated-borders-button-link-5/index.html",
"/mini-projects/",
"/mini-projects/animated-borders-button-link-5/",
"/mini-projects/animated-borders-button-link-5/style.css",
"/mini-projects/animation-test-6/index.html",
"/mini-projects/animation-test-6/",
"/mini-projects/animation-test-6/style.css",
"/mini-projects/background-with-linear-gradient-css-7/index.html",
"/mini-projects/background-with-linear-gradient-css-7/",
"/mini-projects/background-with-linear-gradient-css-7/style.css",
"/mini-projects/button-blur-unblur-28/index.html",
"/mini-projects/button-blur-unblur-28/",
"/mini-projects/button-blur-unblur-28/style.css",
"/mini-projects/circle-8/index.html",
"/mini-projects/circle-8/",
"/mini-projects/circle-8/style.css",
"/mini-projects/flex-grid-32/index.html",
"/mini-projects/flex-grid-32/",
"/mini-projects/flex-grid-32/style.css",
"/mini-projects/heading-33/index.html",
"/mini-projects/heading-33/",
"/mini-projects/heading-33/style.css",
"/mini-projects/hide-show-on-resize-35/index.html",
"/mini-projects/hide-show-on-resize-35/",
"/mini-projects/hide-show-on-resize-35/style.css",
"/mini-projects/html-symbols-36/index.html",
"/mini-projects/html-symbols-36/",
"/mini-projects/html-symbols-36/style.css",
"/mini-projects/index.html",
"/mini-projects/light-and-dark-design-29/index.html",
"/mini-projects/light-and-dark-design-29/",
"/mini-projects/light-and-dark-design-29/style.css",
"/mini-projects/palette-generator-using-css-34/index.html",
"/mini-projects/palette-generator-using-css-34/",
"/mini-projects/palette-generator-using-css-34/style.css",
"/mini-projects/project-ideas/index.html",
"/mini-projects/project-ideas/",
"/mini-projects/project-ideas/style.css",
"/mini-projects/responsive-web-design-2/index.html",
"/mini-projects/responsive-web-design-2/",
"/mini-projects/responsive-web-design-2/script.js",
"/mini-projects/responsive-web-design-2/style.css",
"/mini-projects/sun-and-moon-css-31/index.html",
"/mini-projects/sun-and-moon-css-31/",
"/mini-projects/sun-and-moon-css-31/style.css",
"/mini-projects/textarea-24/index.html",
"/mini-projects/textarea-24/",
"/mini-projects/textarea-24/style.css",
"/mini-projects/tpl-project-mini-0/index.html",
"/mini-projects/tpl-project-mini-0/",
"/mini-projects/tpl-project-mini-0/style.css",
"/mini-projects-list.html",
"/other-projects/index.html",
"/other-projects/",
"/other-projects/php-fuWebsiteToPWA/index.php",
"/other-projects/php-fuWebsiteToPWA/",
"/other-projects/php-fuWebsiteToPWA/php-fuWebsiteToPWA.php",
"/other-projects/php-fuWebsiteToPWA/php-fuWebsiteToPWA2HidenExt.php",
"/other-projects/python-hello-world/main.py",
"/other-projects/python-hello-world/",
"/other-projects-list.html",
"/pages.html",
"/photos/0-100/branch-10.jpg",
"/photos/",
"/photos/0-100/",
"/photos/0-100/branch-9.jpg",
"/photos/0-100/droplets-and-branch-3.jpg",
"/photos/0-100/droplets-and-branch-4.jpg",
"/photos/0-100/droplets-and-branch-5.jpg",
"/photos/0-100/droplets-branch-7.jpg",
"/photos/0-100/flower-15.jpg",
"/photos/0-100/flower-17.jpg",
"/photos/0-100/flower-2.jpg",
"/photos/0-100/flower-6.jpg",
"/photos/0-100/frog-11.jpg",
"/photos/index.html",
"/photos-page.html",
"/pinterest-bb1de.html",
"/projects/agi-countdown-59/data-list.html",
"/projects/",
"/projects/agi-countdown-59/",
"/projects/agi-countdown-59/index.html",
"/projects/agi-countdown-59/script.js",
"/projects/agi-countdown-59/style.css",
"/projects/average-number-40/index.html",
"/projects/average-number-40/",
"/projects/average-number-40/script.js",
"/projects/average-number-40/style.css",
"/projects/background-colors-list-50/index.html",
"/projects/background-colors-list-50/",
"/projects/background-colors-list-50/script.js",
"/projects/background-colors-list-50/style.css",
"/projects/blog-1/index.html",
"/projects/blog-1/",
"/projects/blog-1/script (copy 1).js",
"/projects/blog-1/script.js",
"/projects/blog-1/style.css",
"/projects/browser-info-test-js-2/index.html",
"/projects/browser-info-test-js-2/",
"/projects/browser-info-test-js-2/script.js",
"/projects/browser-info-test-js-2/style.css",
"/projects/calculator-3/index.html",
"/projects/calculator-3/",
"/projects/calculator-3/script.js",
"/projects/calculator-3/style.css",
"/projects/color-picker-4/index.html",
"/projects/color-picker-4/",
"/projects/color-picker-4/script.js",
"/projects/color-picker-4/style.css",
"/projects/count-symbol-39/index.html",
"/projects/count-symbol-39/",
"/projects/count-symbol-39/script.js",
"/projects/count-symbol-39/style.css",
"/projects/demo-test-style-5/index.html",
"/projects/demo-test-style-5/",
"/projects/demo-test-style-5/script.js",
"/projects/demo-test-style-5/style.css",
"/projects/drawing-7/index.html",
"/projects/drawing-7/",
"/projects/drawing-7/script.js",
"/projects/drawing-7/style.css",
"/projects/effect-when-scroll-48/index.html",
"/projects/effect-when-scroll-48/",
"/projects/effect-when-scroll-48/script.js",
"/projects/effect-when-scroll-48/style.css",
"/projects/game-dice-9/index.html",
"/projects/game-dice-9/",
"/projects/game-dice-9/script.js",
"/projects/game-dice-9/style.css",
"/projects/game-guess-number-10/index.html",
"/projects/game-guess-number-10/",
"/projects/game-guess-number-10/script.js",
"/projects/game-guess-number-10/style.css",
"/projects/game-memory-symbol-11/index.html",
"/projects/game-memory-symbol-11/",
"/projects/game-memory-symbol-11/script.js",
"/projects/game-memory-symbol-11/style.css",
"/projects/game-snake-12/index.html",
"/projects/game-snake-12/",
"/projects/game-snake-12/script.js",
"/projects/game-snake-12/style.css",
"/projects/game-tic-tac-toe-13/index.html",
"/projects/game-tic-tac-toe-13/",
"/projects/game-tic-tac-toe-13/script.js",
"/projects/game-tic-tac-toe-13/style.css",
"/projects/google-programmable-search-49/clean.html",
"/projects/google-programmable-search-49/",
"/projects/google-programmable-search-49/index.html",
"/projects/google-programmable-search-49/script.js",
"/projects/google-programmable-search-49/style.css",
"/projects/google-trends-46/index.html",
"/projects/google-trends-46/",
"/projects/google-trends-46/script.js",
"/projects/google-trends-46/style.css",
"/projects/highlight-word-15/index.html",
"/projects/highlight-word-15/",
"/projects/highlight-word-15/script.js",
"/projects/highlight-word-15/style.css",
"/projects/index.html",
"/projects/insert-icon-17/demo.js",
"/projects/insert-icon-17/",
"/projects/insert-icon-17/index.html",
"/projects/insert-icon-17/old-emoji-script (copy 1).js",
"/projects/insert-icon-17/old-material-icon-script.js",
"/projects/insert-icon-17/script.js",
"/projects/insert-icon-17/style.css",
"/projects/lag-test-47/index.html",
"/projects/lag-test-47/",
"/projects/lag-test-47/script.js",
"/projects/lag-test-47/style.css",
"/projects/movie-list-19/index.html",
"/projects/movie-list-19/",
"/projects/movie-list-19/script.js",
"/projects/movie-list-19/style.css",
"/projects/music-20/index.html",
"/projects/music-20/",
"/projects/music-20/script.js",
"/projects/music-20/style.css",
"/projects/navigation-54/demo.js",
"/projects/navigation-54/",
"/projects/navigation-54/index.html",
"/projects/navigation-54/script.js",
"/projects/navigation-54/style.css",
"/projects/print-53/index.html",
"/projects/print-53/",
"/projects/print-53/script.js",
"/projects/print-53/style.css",
"/projects/pwa-test-21/index.html",
"/projects/pwa-test-21/",
"/projects/pwa-test-21/manifest.webmanifest",
"/projects/pwa-test-21/script.js",
"/projects/pwa-test-21/style.css",
"/projects/pwa-test-21/sw.js",
"/projects/quiz-42/index.html",
"/projects/quiz-42/",
"/projects/quiz-42/script (copy 1).js",
"/projects/quiz-42/script (copy 2).js",
"/projects/quiz-42/script.js",
"/projects/quiz-42/style.css",
"/projects/quiz-word-45/index.html",
"/projects/quiz-word-45/",
"/projects/quiz-word-45/script (copy 1).js",
"/projects/quiz-word-45/script.js",
"/projects/quiz-word-45/style.css",
"/projects/radio-22/index.html",
"/projects/radio-22/",
"/projects/radio-22/script.js",
"/projects/radio-22/style.css",
"/projects/rain-38/index.html",
"/projects/rain-38/",
"/projects/rain-38/script.js",
"/projects/rain-38/style.css",
"/projects/random-color-generator-51/demo.js",
"/projects/random-color-generator-51/",
"/projects/random-color-generator-51/index.html",
"/projects/random-color-generator-51/script.js",
"/projects/random-color-generator-51/style.css",
"/projects/random-symbol-23/index.html",
"/projects/random-symbol-23/",
"/projects/random-symbol-23/script.js",
"/projects/random-symbol-23/style.css",
"/projects/random-text-generator-24/index.html",
"/projects/random-text-generator-24/",
"/projects/random-text-generator-24/script.js",
"/projects/random-text-generator-24/style.css",
"/projects/redirects-25/index.html",
"/projects/redirects-25/",
"/projects/redirects-25/script.js",
"/projects/redirects-25/style.css",
"/projects/sorting-55/index.html",
"/projects/sorting-55/",
"/projects/sorting-55/script.js",
"/projects/sorting-55/style.css",
"/projects/speed-dial-58/index.html",
"/projects/speed-dial-58/",
"/projects/speed-dial-58/script.js",
"/projects/speed-dial-58/style.css",
"/projects/start-page-41/index.html",
"/projects/start-page-41/",
"/projects/start-page-41/script.js",
"/projects/start-page-41/style.css",
"/projects/test-27/README.md",
"/projects/test-27/",
"/projects/test-27/cursor-hl.png",
"/projects/test-27/cursor-hl.psd",
"/projects/test-27/index.html",
"/projects/test-27/manifest.webmanifest",
"/projects/test-27/screenshot.png",
"/projects/test-27/script.js",
"/projects/test-27/style.css",
"/projects/test-27/sw.js",
"/projects/text-to-binary-52/index.html",
"/projects/text-to-binary-52/",
"/projects/text-to-binary-52/script.js",
"/projects/text-to-binary-52/style.css",
"/projects/text-to-url-43/index.html",
"/projects/text-to-url-43/",
"/projects/text-to-url-43/script.js",
"/projects/text-to-url-43/style.css",
"/projects/time-binary-clock-28/index.html",
"/projects/time-binary-clock-28/",
"/projects/time-binary-clock-28/script.js",
"/projects/time-binary-clock-28/style.css",
"/projects/time-clock-29/index.html",
"/projects/time-clock-29/",
"/projects/time-clock-29/script.js",
"/projects/time-clock-29/style.css",
"/projects/time-stopwatch-30/index.html",
"/projects/time-stopwatch-30/",
"/projects/time-stopwatch-30/script.js",
"/projects/time-stopwatch-30/style.css",
"/projects/time-utc-clock-56/index.html",
"/projects/time-utc-clock-56/",
"/projects/time-utc-clock-56/script.js",
"/projects/time-utc-clock-56/style.css",
"/projects/todo-list-idea-32/index.html",
"/projects/todo-list-idea-32/",
"/projects/todo-list-idea-32/script.js",
"/projects/todo-list-idea-32/style.css",
"/projects/todo-list-task-31/index.html",
"/projects/todo-list-task-31/",
"/projects/todo-list-task-31/script.js",
"/projects/todo-list-task-31/style.css",
"/projects/tpl-project-001/index.html",
"/projects/tpl-project-001/",
"/projects/tpl-project-001/script.js",
"/projects/tpl-project-001/style.css",
"/projects/tpl-project-app-fixme-sw-002/README.md",
"/projects/tpl-project-app-fixme-sw-002/",
"/projects/tpl-project-app-fixme-sw-002/index.html",
"/projects/tpl-project-app-fixme-sw-002/manifest.webmanifest",
"/projects/tpl-project-app-fixme-sw-002/screenshot.png",
"/projects/tpl-project-app-fixme-sw-002/script.js",
"/projects/tpl-project-app-fixme-sw-002/style.css",
"/projects/tpl-project-app-fixme-sw-002/sw.js",
"/projects/transliterate-35/index.html",
"/projects/transliterate-35/",
"/projects/transliterate-35/script.js",
"/projects/transliterate-35/style.css",
"/projects/tv-36/index.html",
"/projects/tv-36/",
"/projects/tv-36/script.js",
"/projects/tv-36/style.css",
"/projects/typing-speed-14/index.html",
"/projects/typing-speed-14/",
"/projects/typing-speed-14/script.js",
"/projects/typing-speed-14/style.css",
"/projects/video-18/index.html",
"/projects/video-18/",
"/projects/video-18/script.js",
"/projects/video-18/style.css",
"/projects/weather-37/index.html",
"/projects/weather-37/",
"/projects/weather-37/script.js",
"/projects/weather-37/style.css",
"/projects/worst-website-in-the-world-57/README.md",
"/projects/worst-website-in-the-world-57/",
"/projects/worst-website-in-the-world-57/index.html",
"/projects/worst-website-in-the-world-57/screenshot.png",
"/projects/worst-website-in-the-world-57/script.js",
"/projects/worst-website-in-the-world-57/style.css",
"/projects-list.html",
"/robots.txt",
"/rss.xml",
"/search.html",
"/settings.html",
"/sitemap.html",
"/sitemap.xml",
"/sw.js",
"/templates/about-me-page-auto-light-dark-21/index.html",
"/templates/",
"/templates/about-me-page-auto-light-dark-21/",
"/templates/about-me-page-auto-light-dark-21/style.css",
"/templates/card-page-auto-light-dark-20/image.png",
"/templates/card-page-auto-light-dark-20/",
"/templates/card-page-auto-light-dark-20/index.html",
"/templates/card-page-auto-light-dark-20/page.html",
"/templates/card-page-auto-light-dark-20/style.css",
"/templates/clean-one-page-mini-auto-light-dark-16/index.html",
"/templates/clean-one-page-mini-auto-light-dark-16/",
"/templates/clean-one-page-mini-auto-light-dark-16/style.css",
"/templates/flower-one-page-mini-auto-light-dark-flat-17/flower.svg",
"/templates/flower-one-page-mini-auto-light-dark-flat-17/",
"/templates/flower-one-page-mini-auto-light-dark-flat-17/index.html",
"/templates/flower-one-page-mini-auto-light-dark-flat-17/style.css",
"/templates/home-page-auto-light-dark-flat-9/css/style.css",
"/templates/home-page-auto-light-dark-flat-9/",
"/templates/home-page-auto-light-dark-flat-9/css/",
"/templates/home-page-auto-light-dark-flat-9/index.html",
"/templates/home-page-auto-light-dark-flat-9/menu.html",
"/templates/home-page-auto-light-dark-flat-9/page.html",
"/templates/home-page-flat-auto-many-colors-themes-10/css/auto.css",
"/templates/home-page-flat-auto-many-colors-themes-10/",
"/templates/home-page-flat-auto-many-colors-themes-10/css/",
"/templates/home-page-flat-auto-many-colors-themes-10/css/d-blue.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/d-green.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/d-orange.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/d-pink.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/d-plum.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/d-purple.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/d-red.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/d-sea.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/d-violet.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/d-yellow.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/dark.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/empty.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/h-contrast-d.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/h-contrast-l.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/hight-contrast-dark.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/hight-contrast-light.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/l-blue.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/l-green.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/l-olive.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/l-orange.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/l-pink.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/l-plum.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/l-purple.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/l-red.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/l-sea.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/l-seashell.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/l-violet.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/l-yellow.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/light.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/o-blue.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/o-green.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/o-lime.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/o-mint.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/o-olive.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/o-orange.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/o-pink.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/o-plum.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/o-purple.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/o-sea.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/o-silver.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/o-violet.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/o-yellow.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/od-blue.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/od-brown.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/od-forest.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/od-gray.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/od-green.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/od-olive.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/od-pink.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/od-plum.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/od-purple.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/od-red.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/od-sea.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/od-slate.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/od-violet.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/od-yellow.css",
"/templates/home-page-flat-auto-many-colors-themes-10/css/style.css",
"/templates/home-page-flat-auto-many-colors-themes-10/index.html",
"/templates/home-page-flat-auto-many-colors-themes-10/menu.html",
"/templates/home-page-flat-auto-many-colors-themes-10/page.html",
"/templates/home-page-flat-auto-many-colors-themes-10/script.js",
"/templates/home-page-flat-auto-many-colors-themes-10/theme-options.js",
"/templates/home-page-flat-auto-many-colors-themes-10/theme.html",
"/templates/index.html",
"/templates/movie-flat-auto-light-dark-11/index.html",
"/templates/movie-flat-auto-light-dark-11/",
"/templates/movie-flat-auto-light-dark-11/movie-id.html",
"/templates/movie-flat-auto-light-dark-11/movie-poster.png",
"/templates/movie-flat-auto-light-dark-11/movie-poster2.png",
"/templates/movie-flat-auto-light-dark-11/name.html",
"/templates/movie-flat-auto-light-dark-11/search.html",
"/templates/movie-flat-auto-light-dark-11/style.css",
"/templates/personal-2/index.html",
"/templates/personal-2/",
"/templates/personal-2/style.css",
"/templates/personal-3/index.html",
"/templates/personal-3/",
"/templates/personal-3/style.css",
"/templates/photo-gallery-one-page-flat-auto-light-dark-18/index.html",
"/templates/photo-gallery-one-page-flat-auto-light-dark-18/",
"/templates/photo-gallery-one-page-flat-auto-light-dark-18/style.css",
"/templates/profile-card-flat-mini-auto-light-dark-12/index.html",
"/templates/profile-card-flat-mini-auto-light-dark-12/",
"/templates/profile-card-flat-mini-auto-light-dark-12/style.css",
"/templates/profile-card-mini-flat-auto-light-dark-14/index.html",
"/templates/profile-card-mini-flat-auto-light-dark-14/",
"/templates/profile-card-mini-flat-auto-light-dark-14/style.css",
"/templates/saas-landing-page-auto-light-dark-19/index.html",
"/templates/saas-landing-page-auto-light-dark-19/",
"/templates/saas-landing-page-auto-light-dark-19/login.html",
"/templates/saas-landing-page-auto-light-dark-19/product.png",
"/templates/saas-landing-page-auto-light-dark-19/product2.png",
"/templates/saas-landing-page-auto-light-dark-19/product3.png",
"/templates/saas-landing-page-auto-light-dark-19/product4.png",
"/templates/saas-landing-page-auto-light-dark-19/style (copy 1).css",
"/templates/saas-landing-page-auto-light-dark-19/style.css",
"/templates/simple-4/index.html",
"/templates/simple-4/",
"/templates/simple-4/style.css",
"/templates/simple-5/index.html",
"/templates/simple-5/",
"/templates/simple-5/style.css",
"/templates/simple-6/index.html",
"/templates/simple-6/",
"/templates/simple-6/style.css",
"/templates/simple-7/index.html",
"/templates/simple-7/",
"/templates/simple-7/style.css",
"/templates/simple-8/index.html",
"/templates/simple-8/",
"/templates/simple-8/style.css",
"/templates/simple-text-1/index.html",
"/templates/simple-text-1/",
"/templates/simple-text-1/style.css",
"/templates/tpl-0/index.html",
"/templates/tpl-0/",
"/templates/tpl-0/style.css",
"/templates/webdesign-one-page-mini-flat-auto-light-dark-15/circle.svg",
"/templates/webdesign-one-page-mini-flat-auto-light-dark-15/",
"/templates/webdesign-one-page-mini-flat-auto-light-dark-15/coffee.svg",
"/templates/webdesign-one-page-mini-flat-auto-light-dark-15/index.html",
"/templates/webdesign-one-page-mini-flat-auto-light-dark-15/style.css",
"/templates-page.html",
"/text.html",
"/themes.html",
"/video/video.mp4",
"/video/",
"/vscode-theme/README.md",
"/vscode-theme/",
"/vscode-theme/dark-theme-color.json",
"/vscode-theme/icon.png",
"/vscode-theme/index.html",
"/vscode-theme/light-theme-color.json",
"/vscode-theme/package.json",
"/vscode-theme/screenshot-dark.png",
"/vscode-theme/screenshot-light.png",
"/vscode-theme/theme-abc-1.3.57.vsix",
"/vscode-theme/theme-abc-1.5.3.vsix",
"/vscode-theme-page.html",
"/web-search.html",
"/",];
fileListArr.push("no_exit_file_name_for_test.hmtl");

//https://stackoverflow.com/questions/9229645/remove-duplicate-values-from-js-array
fileListArr = [...new Set(fileListArr)]; 




fileListArr.forEach((file) => {
//https://stackoverflow.com/questions/68595209/js-fetch-check-if-file-present-without-downloading-content

//file = '/' + file;

//rm ext
var newFile = hideLinkExt(file);



// with ext
fetch(
file, { method: "HEAD" }
)
.then((res) => {
if (res.ok) {
// file is present at URL
console.log('try cache.add ' + file);
//https://web.dev/learn/pwa/caching/
caches.open("v.1.2.2024.03.20")
.then(cache => {
cache.add(file); // it stores only one resource
//  cache.addAll(["styles.css", "app.js"]); // it stores two resources
});
} else {
console.log('404 not found ' + file);
// file is not present at URL
}
});


// no ext
fetch(
newFile, { method: "HEAD" }
)
.then((res) => {
if (res.ok) {
// file is present at URL
console.log('try cache.add ' + newFile);
//https://web.dev/learn/pwa/caching/
caches.open("v.1.2.2024.03.20")
.then(cache => {
cache.add(newFile); // it stores only one resource
//  cache.addAll(["styles.css", "app.js"]); // it stores two resources
});
} else {
console.log('404 not found ' + newFile);
// file is not present at URL
}
});


});



});

}




// rm old cache
//https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage/delete
this.addEventListener("activate", (event) => {
  const cachesToKeep = ["v.1.2.2024.03.20"];

  event.waitUntil(
    caches.keys().then((keyList) =>
      Promise.all(
        keyList.map((key) => {
          if (!cachesToKeep.includes(key)) {
            return caches.delete(key);
          }
        }),
      ),
    ),
  );
});




// read cache

/*//https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#basic_architecture
const cacheFirst = async (request) => {
  const responseFromCache = await caches.match(request, {ignoreSearch: true});
  if (responseFromCache) {
    return responseFromCache;
  }
return fetch(request);
};

self.addEventListener("fetch", (event) => {
  event.respondWith(cacheFirst(event.request));
});*/

//https://web.dev/learn/pwa/serving
// cache first
self.addEventListener("fetch", event => {
   event.respondWith(
     caches.match(event.request, {ignoreSearch: true})
     .then(cachedResponse => {
       // It can update the cache to serve updated content on the next request
return cachedResponse || fetch(event.request);
     }
   )
  )
});


